### ISSUE TITLE
Cover Editor Lines Don't Wrap, Line Breaks Not Honored

### ISSUE THREAD

**Issue by ehewitt** [MakerPress/atlas-public-feedback#110]
The cover editor does not honor line breaks in the title, though the text box in which you can edit them suggests you can have line breaks. 

My book has a long title, and the title just runs off the page without wrapping; the text is chopped off in both the preview image in the UI, and in the generated .png.

Perhaps text on the cover should automatically wrap? Or constrain the user to the width they are actually allowed so they can't do something invalid? Or let the line breaks on the cover match the line breaks entered in the cover text editor?

**Comment by odewahn** [comment]
Hey, Eben.  You have to enter manual breaks into the cover editor to break a line.  I've done that on your repo, and I've changes some of the font-sizes and positionings so that it looks decent.  Give it a look.  

Andrew

ps -- the cover generator is really meant as a sort of "minimum viable cover".  We're working on a way to upload the "real" cover image that would come from design.

----- Original Message -----
