### ISSUE TITLE
Internal quotes not rendering in Vintage Tomorrows

### ISSUE THREAD

**Issue by courtneynash** [MakerPress/atlas-public-feedback#131]
We have this issue all over the place, because it is a very conversation-heavy book. One example is line 175 of Chapter 5. 

The text in Atlas is: 

"But it’s true," Kaja help up her hands, a helpless servant of the truth. "Before we started going to steampunk conventions my friend Jilly said to me, 'Oh you should go to this thing called http://www.etsy.com[Etsy] and do a search for steampunk.' So I did and there were eight pages of stuff+++...+++

But in the rendered PDF, the internal quotes aren't there, so it looks like this:

"But it’s true," Kaja help up her hands, a helpless servant of the truth. "Before we started going to steampunk conventions my friend Jilly said to me, Oh you should go to this thing called Etsy and do a search for steampunk. So I did and there were eight pages of stuff+++...+++

I fear this is going to make our copyedit/proof round rather painful. Help?

**Comment by sandersk** [comment]
Hi Courtney,

In AsciiDoc, single-quote characters around a phrase are used to signal that the phrase should be in italics, not that it should be surrounded in single quotes (see here if you're interested in more details on AsciiDoc's inline markup: http://www.methods.co.nz/asciidoc/chunked/ch10.html). So that's why the quote characters are disappearing from the text.

The single-quoted text would normally be rendered in italics, but you're not seeing that because of the bug you previously reported in #130.

There are two markup options you can use to do standard single quotes in AsciiDoc:
1. Surround the text on the left with a backtick character, and on the right with a standard apostrophe character:
   
   ```
     `This text will appear in single quotes'
   ```
2.  Use actual curly-quote characters in your text like this:
   
   ```
      ‘This text will also appear in single quotes’
   ```

(On the Mac, you can do a curly left single quote by hitting Option-right-bracket, and a curly right single quote by hitting Option-Shift-right-bracket.)

Perhaps the copyeditor can assist with this task if needed. Once the italics are restored to the PDF, it should be easy to identify those sections within quotations that need the quote markup fixed.

Hope this helps,
Sanders
