### ISSUE TITLE
creating tables in atlas

### ISSUE THREAD

**Issue by nanliu** [MakerPress/atlas-public-feedback#133]
We discussed this with our editor @courtneynash, and we need some assistance creating a table in atlas. There's two tricky issues, one we want to embed code example in a table, another embed images in a table. Please provide an example per atlas documentation:

"Atlas table styles vary slightly between series are supplied by the template stylesheets. If your material warrants something other than the default style as shown in Table 4­2, please consult with your editor."

**Comment by sandersk** [comment]
Hi @nanliu,

We can certainly provide some markup examples for you for embedding code and/or image elements in tables. However, we generally recommend against utilizing tables for purposes other than representing data that is best displayed in rows and columns. The reason for this is that tables containing large quantities of content in each cell do not render well in certain ebook formats (most notably on Kindle), and often result in a lower-quality reading experience for customers.

Do you have examples you could point us to of the code and image content you'd like to display in tables? If so, we'd be happy to take a look and advise on formatting that we can use to ensure the best results on all ereading platforms, as well as print.

Thanks,
Sanders

**Comment by nanliu** [comment]
See https://gist.github.com/2850e0f8de394a6c3a33. FYI @bodepd, you should follow this issue as well.

**Comment by nanliu** [comment]
@sandersk, any updates?

**Comment by sandersk** [comment]
Hi @nanliu and @bodepd,

Apologies for the delayed response, and thanks for the example tables. Do you feel it's important that this content be displayed tabularly, or could it instead be rendered sequentially (which would produce better results in reflowable formats like EPUB and Mobi). For example, would it be feasible to display the code example(s) and then place the figure below them, using cross references to indicate that the image is associated with the code.

For example, here's one potential way we could do example 2:

```
<<Example1>> outlines the manifest, and <<Figure1>> illustrates it in a diagram.

[[Example1]]
.Puppet manifest
====
[source, puppet]
----
package {'apache2':
...
----
====

[[Figure1]]
.Diagram of manifest in <<Example1>>
image::diagram.png[]
```

Let me know what you think, and if this handling would work for you.

Thanks,
Sanders

**Comment by bodepd** [comment]
@sandersk that code was including in tables to highlight the minor differences between the code sections. Printing this information sequentially will make it much harder to highlight these differences.

Is there any other way to perform a vertical split between two sections? What about just using a single image instead of a table?

**Comment by sandersk** [comment]
@bodepd Yes, in this case, I think the best bet might be to capture both the code and the corresponding diagram as a single image. Generally this renders much better on reflowable devices like the Kindle than using a table. Does that work OK for you?

Sanders

**Comment by bodepd** [comment]
@sandersk that works for me. How can I ensure that the code in the output will be colorized consistently with the rest of the code examples?

**Comment by sandersk** [comment]
@bodepd Great question. I can see a couple ways we can deal with the syntax highlighting in the code images. The easiest way might be to temporarily put the code in book marked up as a code listing as usual, e.g.

## [source, puppet]

## manifest here

And then generate a PDF that contains the highlighted code, and then take a screenshot of that for your image. I can also give you a list of the hex color codes we use for each code element, if that's helpful. Let me know.

Please do let me know if that seems like an undue amount of effort for you, though, because our Illustration team can help with this, too.

Thanks,
Sanders
