### ISSUE TITLE
Missing Figures in Atmospheric Monitoring with Arduino PDFs

### ISSUE THREAD

**Issue by bjepson** [MakerPress/atlas-public-feedback#138]
Hi,

I know this book is in production, so perhaps it's in flux, but I wasn't able to build a PDF with images. It looks like it's because images/ was renamed to figs/. 

If this change is part of the intake/production process, could we add support for the figs/ directory to the build process?

See: http://ano-atlas2.herokuapp.com/books/1230000000233

Thanks,

Brian

**Comment by sandersk** [comment]
Hi Brian,

I just built a PDF in Atlas, and images were being included just fine. I suspect the PDF previously on the dashboard was just generated before the image filenames and AsciiDoc references were synced back up, because Atlas definitely supports pulling down the images regardless of directory name.

Could you take a look at the latest PDF on the dashboard and let me know if you see any further issues?

Thanks,
Sanders

**Comment by bjepson** [comment]
Thanks, Sanders! You're right; I must have kicked off that PDF build while things were in an in-between state.
