### ISSUE TITLE
PHP formatting problem

### ISSUE THREAD

**Issue by jhodgdon-drp** [MakerPress/atlas-public-feedback#142]
I am trying to format some PHP code that is embedded in HTML markup (this is legal PHP syntax), and it is coming out a bit ugly. Here is what I have put into my .asciidoc file:

```
[source,php]
----
// Same output as a theme template file.
<div><?php print $input1; ?></div>
----
```

I would expect the formatting for the `<div>` and the `</div>` tags to be the same, and I would expect the formatting for the `<?php` and the closing `?>` tag to be the same. Instead, I am seeing the closing DIV tag in red, and the closing PHP tag in light blue (the opening tags are both dark blue). This is in the PDF output of my book on page 15.

I would like to attach a screen shot, but I do not see how to do that in an issue... and sorry for the edits, I got the code formatting wrong the first times. :)

**Comment by sandersk** [comment]
Hi Jennifer,

Unfortunately, there's no built-in UI support in the GitHub issue tracker for uploading images. I wish it supported screenshots, too :)

For code examples like the one you cited, where the PHP code is embedded in HTML, I would suggest using:

```
[source,html+php]
```

Instead of:

```
[source,php]
```

The html+php module does a better job of highlighting the HTML bits and the PHP bits properly. Could you give that a try and see if you like the results better?

Thanks,
Sanders

**Comment by jhodgdon-drp** [comment]
I'll give that a try and report back tomorrow. Thanks!

**Comment by jhodgdon-drp** [comment]
That works OK... the formatting for PHP bits is not as nice as the [source,php] formatter, but at least it doesn't totally punt on the HTML bits. It will do. Thanks!
