### ISSUE TITLE
Can't change title of book on title page of PDF

### ISSUE THREAD

**Issue by meisenberg-oreilly** [MakerPress/atlas-public-feedback#172]
When I change the title of my book (under "Admin"), the change is reflected in the Atlas UI, but the original title is displayed on the title page of the generated PDF.

Adding a <title> element to book-docinfo.xml doesn't work; that yields a title page displaying both the old and the new title.

**Comment by meisenberg-oreilly** [comment]
I worked around this issue by editing book.asciidoc via git.

**Comment by sandersk** [comment]
Hi Michael,

Due to a current quirk in the Atlas build system, when you update title metadata in the Admin tab, in order to have it reflected in the build, you need to "force-regenerate" the book.asciidoc file via the UI by moving a file from the "Files to Build" column to the "Files to Ignore" column, and then back to the "Files to Build" column; otherwise a cached version of the previous book.asciidoc with the old title is used. Or, you can do what you just did, which is to update the book.asciidoc file manually via Git.

We're working on a more elegant fix to the UI workaround specified above, as we realize it's not ideal.

Hope this helps. Let us know if you encounter any further issues.

Thanks,
Sanders
