### ISSUE TITLE
New files not showing up in "build" page

### ISSUE THREAD

**Issue by paulbakker** [MakerPress/atlas-public-feedback#175]
After adding some new files they do show up on the dashboard, but not on the build page. See screenshots for an example.

![Screen Shot 2013-01-01 at 16 03 02 ](https://f.cloud.github.com/assets/109484/37284/86c1218a-5424-11e2-8f39-808431cec4e6.png)
![Screen Shot 2013-01-01 at 16 03 11 ](https://f.cloud.github.com/assets/109484/37285/8b405384-5424-11e2-9377-3f87222f2d84.png)

**Comment by sandersk** [comment]
Hi Paul,

In order to show up in the lists on the Build tab, files must have an extension of .asciidoc, so that's why you don't see 03-advanced-osgi or book-toc.txt. If you rename these files to have a .asciidoc extension, that should solve the problem.

Let us know if you encounter any further issues.

Thanks,
Sanders
