### ISSUE TITLE
New interface looks good but...

### ISSUE THREAD

**Issue by raywilson007** [MakerPress/atlas-public-feedback#182]
Hi Folks

The new writing interface looks good but would benefit from some tool tips on the graphic menu and the return of the HTML View button. I found the HTML view helpful for proof reading and image checking.

Best

Ray

**Comment by runemadsen** [comment]
Hi Ray

Thanks! The HTML view can still be found under the "Quick Links" tab. We're working on tooltips for the editor, so stay tuned.

**Comment by odewahn** [comment]
Relatedly, I when there are lots of files (> 10 or so), the "quick links" and "settings" blocks are pushed off the bottom of the screen.  Despite my earlier feedback, it might make sense to have "Settings" and "Quicklinks" above the files, rather than below, so that they cannot be as easily missed.

Andrew

----- Original Message -----

**Comment by JillEd** [comment]
I agree with odewahn about the placement of the Setting and Quicklinks--icons at top of page also need tool tips. Thanks.

Jill Ed

**Comment by runemadsen** [comment]
This has been fixed.
