### ISSUE TITLE
Issue building EPUB and MOBI with my book

### ISSUE THREAD

**Issue by JohnGarbutt** [MakerPress/atlas-public-feedback#198]
The book is: 1230000000605

The error is:

Traceback (most recent call last):
  File "/usr/local/app/worker/.local/bin/db_to_epub", line 137, in <module>
    sys.exit(main())
  File "/usr/local/app/worker/.local/bin/db_to_epub", line 133, in main
    raise e
lxml.etree.XMLSyntaxError: Entity 'rsquo' not defined, line 27, column 26

**Comment by sandersk** [comment]
Hi @JohnGarbutt,

I resolved the "rsquo", "ldquo", and "rdquo" entities in the book to the proper quote characters, and EPUB and Mobi files are now building properly. If you go to the Dashboard, you'll see both file formats now available for download.

If you encounter any further problems or have any questions, please reopen the ticket and let me know.

Thanks,
Sanders

**Comment by deanwampler** [comment]
I'm having this issue, too, with my new book, Programming Scala, 2nd Edition. Is there a way to define these entities in a config file? I'm sure there will be others besides these left and right, single and double quotes.

**Comment by sandersk** [comment]
Hi @deanwampler,

The next release of Atlas will have more sophisticated handling of entities that should eliminate this issue. (In the current version of Atlas, you will only get entity errors if the AsciiDoc doesn't convert to valid XML for ebook generation)

For now, I've gone ahead and resolved all the "rsquo", "ldquo", and "rdquo" entities. I also resolved one instance of `&rArr;` in ch01-IntroducingScala.asciidoc (line 431, "UTF8 &rArr; is also allowed") to a right arrow character (although I'm not sure if you just wanted the entity name to be printed literally here, so you may want to review).

I also corrected a few minor AsciiDoc syntax issues that resulted in invalid XML downstream:
- There were a couple [source] declarations in AsciiDoc that did not specify a language--e.g., `[source]` instead of `[source,java]`. 
- I saw one code listing in a passthrough that was not contained in a `<programlisting>` element. All code-listing passthroughs should be nested in a `<programlisting>` or `<screen>` element.

Good:

```
++++
<programlisting>$ <userinput>echo "Hello World"</userinput></programlisting>
++++
```

Bad:

```
++++
$ <userinput>echo "Hello World"</userinput>
++++
```

PDF, EPUB, and Mobi are now building now for your book. Let me know if you have any questions or run into further issues.

Thanks,
Sanders

**Comment by deanwampler** [comment]
Thanks for the help and sorry I didn't reply sooner.

Dean

On Fri, Jan 3, 2014 at 10:08 AM, Sanders Kleinfeld <notifications@github.com

> wrote:
> 
> Hi @deanwampler https://github.com/deanwampler,
> 
> The next release of Atlas will have more sophisticated handling of
> entities that should eliminate this issue. (In the current version of
> Atlas, you will only get entity errors if the AsciiDoc doesn't convert to
> valid XML for ebook generation)
> 
> For now, I've gone ahead and resolved all the "rsquo", "ldquo", and
> "rdquo" entities. I also resolved one instance of &rArr; in
> ch01-IntroducingScala.asciidoc (line 431, "UTF8 => is also allowed") to a
> right arrow character (although I'm not sure if you just wanted the entity
> name to be printed literally here, so you may want to review).
> 
> I also corrected a few minor AsciiDoc syntax issues that resulted in
> invalid XML downstream:
> 
>    -
> 
>    There were a couple [source] declarations in AsciiDoc that did not
>    specify a language--e.g., [source] instead of [source,java].
>    -
> 
>    I saw one code listing in a passthrough that was not contained in a
>    <programlisting> element. All code-listing passthroughs should be
>    nested in a <programlisting> or <screen> element.
> 
> Good:
> 
> ++++
> <programlisting>$ <userinput>echo "Hello World"</userinput></programlisting>
> ++++
> 
> Bad:
> 
> ++++
> $ echo "Hello World"
> ++++
> 
> PDF, EPUB, and Mobi are now building now for your book. Let me know if you have any questions or run into further issues.
> 
> Thanks,
> Sanders
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/MakerPress/atlas-public-feedback/issues/198#issuecomment-31532082
> .

## 

Dean Wampler, Ph.D.
Typesafe
"Functional Programming for Java Developers",
"Programming Scala", and
"Programming Hive" - all from O'Reilly
twitter: @deanwampler, @chicagoscala
http://typesafe.com
http://polyglotprogramming.com
