### ISSUE TITLE
SVG images?

### ISSUE THREAD

**Issue by simonmar** [MakerPress/atlas-public-feedback#203]
I have several images in my book, which I'm currently creating as SVGs using Inkscape. These look great when I format the book locally, but when built using Atlas the figures have too much vertical space around them (like, most of a page).  I'm using

```
image::1plus2.svg[scaledwidth="30%"]
```

I've tried using `height` instead of `scaledwidth`, but that doesn't give good results either: the image has too much vertical space after it (and it is much smaller when built on Atlas than when built locally).

I could probably convert them to PNG, but these are vector drawings and a bitmap image will almost certainly look worse when printed. Is there another way I should be doing this?

book: http://ano-atlas2.herokuapp.com/books/1230000000929

**Comment by adamwitwer** [comment]
Hi @simonmar,

The problem seems to be related to the SVG files themselves. I opened map.svg in Illustrator and cropped it before regenerating a new PDF. You can see the results in the attached image.

We have illustrators on staff that can help with cropping once your book comes into production, so if you don't want to fix these now, we'll fix them in production.

Adam
![Screen Shot 2013-02-05 at 2 08 01 PM](https://f.cloud.github.com/assets/469435/128802/bedfad48-6fc7-11e2-8a28-a1bfe5e9a41f.png)

**Comment by simonmar** [comment]
Ok, thanks - I didn't realise I needed to crop the images, because they looked fine when I formatted the book on my computer. I should be able to crop them myself, thanks for the tip.
