### ISSUE TITLE
Where are bogus DocBook entities coming from?

### ISSUE THREAD

**Issue by andyoram** [MakerPress/atlas-public-feedback#206]
This problem occurs in 1230000000549. My understanding was that our tools would accept <>& in Asciidoc. I tested the tools with a few entries and the PDF build went fine. But after I finished the whole book, the PDF build aborts with odd references to DocBook entities that are not in the source files. You can view the error report.

**Comment by sandersk** [comment]
Hi Andy,

The errors in the log were due to the use of < and > characters inside passthrough blocks, like this:

```
++++
#include <unistd.h>

int nice (int inc);
++++

```

In passthrough blocks, all characters are passed through literally to the XML output, which resulted in raw text like <unistd.h> that was then misinterpreted as an XML tag.

I believe all the passthrough blocks like the above were intented to be code listings, so I reformatted them as listing blocks, e.g.:

```
----
#include <unistd.h>

int nice (int inc);
++++

----
```

In listing blocks, reserved XML characters like < and > are properly escaped in XML output. Fixes have been committed, and the PDF now successfully builds. You can download the latest PDF I generated from the Dashboard.

If I'm incorrect in my assumption that the passthrough blocks should be listing blocks, let me know, and I can revert the changes I made. Also let me know if there's anything else I can assist with.

Thanks,
Sanders
