### ISSUE TITLE
Side by side images bugs

### ISSUE THREAD

**Issue by markjlyon** [MakerPress/atlas-public-feedback#215]
There are two different bugs when attempting to place images side by side.

Issue 1

If you use any of the following techniques:

image::images/image1.png[]image::images/image2.png[] 
image::images/image1.png[] image::images/image2.png[]
image::images/image1.png[width=256]image::images/image2.png[width=256]
image::images/image1.png[width=256] image::images/image2.png[width=256] 

You will see only one image and it ignores the width directive. I presume the missing image is sitting behind/under the visible image.

Issue 2

If you attempt to place the images in a table to place them side by side:

|====
| image::images/image1.png[width=256] | image::images/image2.png[width=256]
|====

You will see the two image placeholders where the images should be.

**Comment by sandersk** [comment]
Hi Mark,

If you use the inline AsciiDoc image macro (one colon after "image" instead of two) in your table markup, you should get the desired rendering. For example:

```
|====
| image:images/image1.png[width=256] | image:images/image2.png[width=256]
|====
```

Note, though, that in Production, as part of our Illustration work, we'll most likely be processing the two side-by-side images into one composite image, which is scaled appropriately, so the table is really just a temporary method of achieving this effect in the short term. If you could add a comment to this effect in the source, so that Illustration is aware of the desired side-by-side rendering, that would be great.

Thanks,
Sanders
