### ISSUE TITLE
I want to see book.asciidoc

### ISSUE THREAD

**Issue by tobrien** [MakerPress/atlas-public-feedback#219]
I'm just being picky, I know.   But, as I'm writing this the only hint that there is a book.asciidoc is in the build tab.    I have to edit the book.asciidoc locally and then copy it up.     I'd like to be able to edit it through the web interface.

On the Build tab I can rearrange chapters, but I don't think that's making a commit back to git.

**Comment by runemadsen** [comment]
Hi again. This is definitely an area that needs to be improved in Atlas. 

We are actually committing directly to the book.asciidoc file if you move things around in the file listing. However, if you have extra stuff in there (like text), it will be deleted. 

We ignored the book.asciidoc file, because we were afraid people would be confused to see it pop up. Maybe we were wrong.
