### ISSUE TITLE
Error ePub in TOC Kobo Glo

### ISSUE THREAD

**Issue by michaeljamesfitzgerald** [MakerPress/atlas-public-feedback#237]
Received an errata about how the TOC of the ePub version of Introducing Regular Expressions doesn't work on a Kobo Glo. Please see the following errata for details.

http://www.oreillynet.com/cs/portal/view/errata/140042
http://www.oreillynet.com/cs/portal/view/errata/140043

These attribute values are changed "under the hood" and there is not a way for me as the author to fix this issue. The main issue appears to be a leading underscore in an attribute value. How can we help the submitter?

Thanks,

Mike

**Comment by sandersk** [comment]
Hi @michaeljamesfitzgerald,

Thanks so much for bringing this issue to our attention. You are indeed correct that this would be something we need to address in our ebook toolchain, not something you'd need to fix in the source files. I will do some testing to confirm I can reproduce the customer's issue and pinpoint the leading underscores (which are technically valid in EPUB) as the cause.

In the meantime, I can certainly regenerate and reload this particular EPUB without leading underscores in the ids. Can you confirm that it's fine to regenerate EPUB from the latest files located in Atlas here (as I see you've made changes to the source files since the book went to press):

http://ano-atlas2.herokuapp.com/books/1230000000565

@nelliemckesson, can you make sure someone on the digiprod or Customer Service team reaches out to the customer and lets him know that we are working on this issue. I'm concerned that because it came through the errata portal rather than more formal customer-service channels that the CS team may not have seen it.

Sanders

**Comment by nelliemckesson** [comment]
Just FYI @sandersk Ive brought this to Customer Service's attention and asked them to make sure the reporter is aware of this thread.
