### ISSUE TITLE
Never-ending build

### ISSUE THREAD

**Issue by DanGitOreilly** [MakerPress/atlas-public-feedback#238]
Several hours ago I kicked off a PDF build of this book: http://ano-atlas2.herokuapp.com/books/1234000001489

It's still running.

Thanks,

Dan

**Comment by sandersk** [comment]
Hi Dan,

Just tried building again right now, and it built successfully, so at least that solves your immediate problem.

We've been having some issues today with hanging builds, so we'll look into that further. Let us know if you encounter further problems.

Thanks,
Sanders

**Comment by runemadsen** [comment]
Thanks Dan. I'll look into this.

**Comment by java-javascript** [comment]
I have noticed that the icon keeps spinning on the page where the build is kicked off, but if I go back to the dashboard, the build completes.

**Comment by sandersk** [comment]
@java-javascript Yes, that's true; right now, the statuses on the Build page aren't automatically updated. But if you refresh the page (or go to the Dashboard page and refresh), you can check whether the build has completed.

One note on refreshing, however, is that Google Chrome has a bug where hitting refresh will retrigger the build again (see #224 for more details), so that's something to be careful about if you're using Chrome.
