### ISSUE TITLE
AsciiDoc error handling -- not stable

### ISSUE THREAD

**Issue by ceteri** [MakerPress/atlas-public-feedback#242]
Getting a lot of fatal errors on book builds today.
Mostly:

[blockdef-listing] missing closing delimiter

Those are for markdown which had worked fine previously.

When I try removing the block listed in the error then some earlier part of the markdown throws a different error.

Is that Atlas release stable?  
Or was there a big delta in recent changes to error handling?

Many thanks -
Paco

**Comment by sandersk** [comment]
Hi Paco,

Yes, the Atlas repo is stable, and there have been no recent changes to error handling.

I took a look at the source files, and there was a markup error with the code listing block in 08_Case_Study.asciidoc starting on line 482:

```
[source,text]
---
?road_name   Hawthorne Avenue from Alma Street to High Street
?geohash     9q9jh0
?road_lat    37.446140860599854
?road_lng    -122.1674652295435
?road_alt    0.0
?road_metric [1.0 0.5488121277250486 0.88]
?tree_metric 4.36321007861036
----
```

The opening delimiter has only three hyphens, instead of the required four. As such, AsciiDoc doesn't recognize the "start code listing" delimiter, and sees the four dashes at the end of the listing as a "start code listing" delimiter instead of an "end code listing" delimiter. This resulted in a cascading series of mismatched delimiters that eventually resulted in the reported error.

I fixed the opening delimiter and was able to rebuild the PDF successfully. Please let me know if you encounter any further issues.

Thanks,
Sanders

**Comment by ceteri** [comment]
Awesome, thank you Sanders!

My fault entirely. I'll keep closer track of the "---" mistake
