### ISSUE TITLE
Images don't maintain aspect ratio

### ISSUE THREAD

**Issue by MikeW50** [MakerPress/atlas-public-feedback#243]
When compiling 

```
Building iPhone and iPad Electronic Projects.
http://ano-atlas2.herokuapp.com/books/1234000000706.
```

to epub, some images appear tall and thin, loosing the original aspect ratio. See, for example, Figure 1-3. The image looks correct in iBooks when you double-tap it to zoom. It also looks correct in the PDF.

**Comment by sandersk** [comment]
Hi @MikeW50,

Please use the following markup for all Figures in the book:

```
[[figure_id]]
.Running and Editing Programs
image::images/Fig_1-3.jpg[]
```

There is no need to hardcode the number in the Figure title, because if you use the above syntax, the "Figure 1-3" label will be automatically added to the caption. If you need to cross-reference the Figure from the body text, you can do so as follows:

```
The screenshot in <<figure_id>> shows an iPhone running and editing programs.
```

If you need to scale an image, please use "width" instead of "height" ("height" is not formally supported):

```
[[figure_id]]
.Running and Editing Programs
image::images/Fig_1-3.jpg[width="3in"]
```

Keep in mind, however, that all images will be processed and sized appropriately by the Illustration staff when the book comes into Production, so you don't need to worry too much about perfect sizing at this time, as long as you're happy with how images are displayed in your output formats.

If you're interested in more information on our AsciiDoc guidelines, you may want to check out Chapter 4 of our Getting Started with Atlas guide, "AsciiDoc 101":

http://chimera.labs.oreilly.com/books/1230000000065/index.html

Hope this helps, and let me know if you have further questions.

Thanks,
Sanders

**Comment by sandersk** [comment]
Closing this ticket, as I'm assuming you're all set here, @MikeW50. Please feel free to reopen if you have further questions or run into additional issues.

Thanks,
Sanders
