### ISSUE TITLE
Multiple builds?

### ISSUE THREAD

**Issue by hexagon5un** [MakerPress/atlas-public-feedback#253]
Hi,

We're just now getting to the phase in my book where an editor and I are working simultaneously.  While the editors are looking at one chapter, reviewing it, I'm largely writing another, although I've made some of their suggested edits as well.

On one hand, the editor would like a stable "build" that's indicative of edit-ready material. On the other hand, for me to see how the new material is going to render, I'd like to see it "built" but I don't want to mess up the editorial flow.  The upshot is that I've been not using the build system as much as I'd like in order to keep not-yet-edit-ready material out of the build section.  

If we were following git-style software-development repo practices, we'd have a writing branch and an editing branch, and separate builds for both of them.  That way, an editor and an author could work in parallel on two different branches, and merge as appropriate.  This doesn't seem possible in Atlas.

Is there something I'm missing?  What's the intended workflow like with respect to the git repo's master branch and the build system?  Is it possible to build branches of the repo other than "master"?  (Is this a question or a feature request?)

Thanks much for listening,
   Elliot.

**Comment by sandersk** [comment]
Hi Elliot,

Great question. Unfortunately, it's not possible at this time to build from a branch other than master. But I think that's a great feature request, so we'll definitely add that to our list for future enhancements.

In the meantime, one way you might be able to work around these limitations would be to set up a separate Atlas project just for those iterative "writing" builds. So you'd have your main Atlas project with two branches--e.g., "master" for the content that was ready for editors to review, and "writing" for the iterative, in-progress stuff you're working on. Then, you'd have a separate Atlas project whose master branch could be synced with the "writing" branch for the main repo, so that you could do a distinct set builds. It'd be a little bit of extra work, but I think that would meet your needs.

If you do go this route, though, please use a name for that separate Atlas project that makes it clear that it's draft content only and not the primary book repo, to eliminate any confusion for editorial or production staff.

Hope this helps. Let us know if you have any further questions or if we can be of more assistance.

Thanks,
Sanders

---

Sanders Kleinfeld
Publishing Technology Engineer
O'Reilly Media Inc.
sanders@oreilly.com
@sandersk

**Comment by odewahn** [comment]
Yep - Sanders' suggestion seems like the best way to go for now.  And, not that it's any particular consolation, we're working on the ability to handle multiple branches in the next major release of Atlas.  Stay tuned!

----- Original Message -----

**Comment by hexagon5un** [comment]
Just to be clear:  I should create a "new book" for the development for the development branch and then push/pull between the repos?  

And I'm stoked to hear that multiple branches is in the next major version. 

Thanks,
  Elliot.

**Comment by sandersk** [comment]
Yes, you can create a "new book" for the development branch and then push/pull as needed. Please do name the new repo so that it's clear that it's a development branch and not the main book repo, though, just to avoid any confusion.

Thanks,
Sanders

**Comment by hexagon5un** [comment]
(Just wasn't sure what you mean by "new project" a few posts ago.)

That's a great idea, and a totally workable workaround.  Thanks again.  

Elliot.
