### ISSUE TITLE
Possible asciidoc problem with escaping?

### ISSUE THREAD

**Issue by jdeisenberg** [MakerPress/atlas-public-feedback#266]
In the following text, the first and second up arrows don't have a backslash before them in the generated PDF; the third one does. This also happens in the HTML generated by a straight asciidoc command from the command line. What am I mis-interpreting about asciidoc?

```
The up-arrow +\^+ matches the beginning of a string, and the dollar
sign +$+ matches the end of a string. Thus, +\^[A-Z]+ matches a capital
letter at the beginning of the string. Note that if you put the +\^+ inside
the square brackets, that would mean something entirely different!
```

**Comment by sandersk** [comment]
Hi @jdeisenberg,

The logic in AsciiDoc governing when you need to escape characters so that they aren't interpreted as markup, and when you don't, is rather complex. For example, in the following sentence:

```
The up-arrow +^+ matches the beginning of a string, and the dollar
sign +$+ matches the end of a string.
```

You don't need to escape the caret because AsciiDoc won't interpret it as an opening-superscript delimiter because there's no matching caret in the same paragraph to serve as the closing-superscript delimiter.

However, in this paragraph:

```
The up-arrow +^+ matches the beginning of a string, and the dollar
sign +$+ matches the end of a string. Here's another up-arrow +^+
```

there are now two carets that will be interpreted as opening and closing superscript delimiters, and you'll end up with superscripted text in the output instead of caret characters if you don't escape properly. However, in this case, you only need to escape the first caret character, not the second caret character, because once the first caret character is escaped and interpreted literally, the second caret character is no longer part of a matching pair and is interpreted literally by default. So for your paragraph above, if you do the markup like this:

```
The up-arrow +\^+ matches the beginning of a string, and the dollar
sign +$+ matches the end of a string. Thus, +\^[A-Z]+ matches a capital
letter at the beginning of the string. Note that if you put the +^+ inside
the square brackets, that would mean something entirely different!
```

You'll get your intended result. 

AsciiDoc is kind of unique in that it treats backslash characters as escapes only in contexts in which an escape would be needed, and otherwise it treats them as literal backslash characters. I personally am not a fan of this behavior, as I feel it can be quite confusing, and also feel that it opens the door for errors when edits are made down the road. For example, if you were to add another sentence with a caret to the above paragraph, you would then need to escape the penultimate caret with a backslash.

Because of this, I would actually recommend for your paragraph that instead of using backslash escapes, you use AsciiDoc's "inline literal passthrough" markup, where instead of using plus signs to delimit monospace content, you use backticks. When backticks are used, it tells AsciiDoc that all content inside should be interpreted literally, so you don't need to use any backslashes to escape. Using this syntax, your paragraph will look like this:

```
The up-arrow `^` matches the beginning of a string, and the dollar
sign `$` matches the end of a string. Thus, `^[A-Z]` matches a capital
letter at the beginning of the string. Note that if you put the `^` inside
the square brackets, that would mean something entirely different!
```

Hope I explained this clearly, and that this info is helpful. Please let me know if you have any further questions or if we can be of additional assistance.

Thanks,
Sanders

**Comment by jdeisenberg** [comment]
Yes, that explains it quite well. Sometimes software can be too helpful.
