### ISSUE TITLE
Emphasis in literal block

### ISSUE THREAD

**Issue by jdeisenberg** [MakerPress/atlas-public-feedback#273]
I am trying to put part of an SVG example in boldface. [subs="quotes"] is definitely not the answer, as you can see from the disastrous results at

http://chimera.labs.oreilly.com/books/1234000000446/ch02.html#svgess-CHP-2-SECT-5

Asciidoc markup is:

```
[subs="quotes"]
----
<svg width="200px" height="200px" viewBox="0 0 200 200">
    <circle cx="25" cy="25" r="25" style="stroke: black; fill: none;"/>
    *<rect x="100" y="5" width="30" height="80"
       style="stroke: blue; fill: none;"/>*
</svg>
----
```

I can do it with a passthrough into Docbook, but I'd like to use pure asciidoc if at all possible.

**Comment by sandersk** [comment]
Hi @jdeisenberg,

Instead of just [subs="quotes"], you should do [subs="specialcharacters, quotes"] as follows:

```
[subs="specialcharacters, quotes"]
----
<svg width="200px" height="200px" viewBox="0 0 200 200">
    <circle cx="25" cy="25" r="25" style="stroke: black; fill: none;"/>
    *<rect x="100" y="5" width="30" height="80"
       style="stroke: blue; fill: none;"/>*
</svg>
----
```

The "specialcharacters" substitution ensures that the < and > are escaped as &amp;lt; and &amp;gt; so that the code listing is rendered literally.

Also, just a reminder that when you add "quotes" to the subs line for a code listing, AsciiDoc will consider the following characters to be markup characters:

```
* ' ` $ _ + # ^ ~
```

So if you intend to use any of these characters literally (not an issue in the above example), and they appear in pairs, you may need to escape them as discussed in #266.

Hope this helps.

Let me know if you have any more questions or run into any difficulties.

Thanks,
Sanders

**Comment by jdeisenberg** [comment]
Thanks; that did the trick.

**Comment by jdeisenberg** [comment]
The fix doesn't seem to work in conjunction with [source, xml]; the PDF produced for chapter 1 doesn't come out well with markup like this:

```
[role="offline_only"]
[source, xml]
[subs="specialcharacters,quotes"]
----
<svg width="140" height="170" 
  xmlns:xlink="http://www.w3.org/1999/xlink">
<circle cx="70" cy="95" r="50" style="stroke: black; fill: none;"/>
<circle cx="55" cy="80" r="5" stroke="black" fill="#339933"/>
<!-- etc -->
</svg>
----
====
```

The output in PDF gives &lt; for the <, &gt; for > , and so on.

**Comment by sandersk** [comment]
Hi @jdeisenberg,

Good catch. Yes, you're correct that custom "subs" declarations don't work with the `[source, ...]` syntax, because the `source` declarations make use of AsciiDoc's Filter feature, which isn't fully user-customizable.

As a workaround, I've come up with an alternative syntax that you can use to specify both a language for syntax highlighting and the "subs" you need in order to do native AsciiDoc inline tagging in a code listing. Please try using the following:

```
[role="offline_only"]
[language="xml"]
[subs="specialcharacters,quotes"]
----
<svg width="140" height="170" 
  xmlns:xlink="http://www.w3.org/1999/xlink">
<circle cx="70" cy="95" r="50" style="stroke: black; fill: none;"/>
<circle cx="55" cy="80" r="5" stroke="black" fill="#339933"/>
<!-- etc -->
</svg>
----
```

Let me know if this meets your needs.

Thanks,
Sanders

**Comment by jdeisenberg** [comment]
I tried this, and began the rebuild. The HTML completed quickly; the PDF is
still pending as of 10 minutes.

**Comment by jhosman** [comment]
Hi @jdeisenberg, your PDF should be built now. We had a problem with another book crashing the Atlas server, so all the builds got stuck. It should be all set now, though.
