### ISSUE TITLE
Addition to documentation

### ISSUE THREAD

**Issue by shelleyp** [MakerPress/atlas-public-feedback#279]
Currently the introduction to Atlas documentation doesn't have anything on JS Bin, or how to use the role=value indicator. 

Documentation does need to be updated to account for both. In particular, I can't figure out from the documentation how to display the sidebar title and contents for online only, but display a poster image for other types of publication. 

If you use [role="online_only"] nothing is displayed in a PDF. However, if you omit this role, then everything is displayed, including the sidebar title and text telling an online reader how to manipulate the example—something I don't want in the PDF. 

I'm assuming an alternative would be to embed the static image in the document for offline modes, only,  but I can't find what a role would be for displaying the content to every type _but_ online. 

In addition, I just noticed that the link to search within the Getting Started with Atlas document is disabled.

**Comment by sandersk** [comment]
Hi @shelleyp,

This is great feedback. We will get detailed documentation on JS Bin interactives into the Getting Started with Atlas guide, but in the meantime here are some answers to your queries:
- If I'm understanding your request correctly, it sounds like you're looking for a way to earmark one section as "online_only" with content tailored for the Web version, and then you'd like to earmark an alternative section with the equivalent of [role="everything_but_online"], so that it shows up in PDF but is suppressed from the Web version. Is that correct? If so, I will go ahead and implement that for you. I agree this is something we should have.
- Search is working for me in the Getting Started with Atlas document; it's actually a field, not a link in the top navbar. If you go here:

http://chimera.labs.oreilly.com/books/1230000000065/index.html

And then click "Search book..." you should get a text insertion point where you can then enter your search term(s). Then hit Enter, and you should get the search results. Let me know if this doesn't work for you, and if not, which browser you're using.

Thanks,
Sanders

**Comment by shelleyp** [comment]
Sanders, what you described is exactly what I hoped for—a way of marking up chunks that go to different media types, particularly online and offline types. 

With this functionality, I can just display a figure for a PDF, while providing a live example in Chimera. 

Many thanks!

Suggestion: the Search Book capability needs to be redefined. You would expect a link like the other menu options. You don't expect to go to the text, and actually start typing. I'm afraid it isn't at all intuitive. My suggestion would be to replace it with a more traditional search field with the search symbol (the idealized magnifying glass). I know this is a user look and feel thing, but when the text didn't change when the mouse cursor was over the text, I thought it was just a broken link. Either that, or Search wasn't implemented yet. 

Anyway, thanks for clarifying what I need to do. And for the work on the new offline role!

Shelley

**Comment by jdeisenberg** [comment]
@shellyp: I have the exact same requirement for a book I'm working on, and have discussed the issue with Sanders. You phrased it much more nicely than I did.

**Comment by sandersk** [comment]
Hi @shelleyp and @jdeisenberg,

I've now added support for the following role:

```
[role="offline_only"]
```

Which will suppress content from the Web output only, but will render it in all other formats (basically, the exact opposite of role="online_only"). Give it a try, and let me know if you have any questions or need anything further.

Thanks,
Sanders

**Comment by shelleyp** [comment]
Works perfectly, Sanders. Thanks!

**Comment by shelleyp** [comment]
I closed this because of the offline fix, but I wonder if I should open a new issue specific to the search field? That's not a bug, it's really a suggestion.

**Comment by sandersk** [comment]
I already opened a separate issue in our project for the Web reading environment, so that our Design team can review, so we're all set there.

**Comment by shelleyp** [comment]
Very cool. Many thanks.
