### ISSUE TITLE
Image quality in offline publications

### ISSUE THREAD

**Issue by shelleyp** [MakerPress/atlas-public-feedback#282]
I have uploaded PNG images for use in my book, but I noticed that the image has degraded significantly in the .mobi generated build. It seems fine with the other builds. 

Are there certain requirements for images that ensure we get a good result in all builds? Is this documented somewhere?

**Comment by sandersk** [comment]
Hi @shelleyp,

Can you point me to a specific example of an image in which the quality is substantially lower in Mobi vs. PDF? This is not typical, so I'd like to take a closer look at what's going on.

Thanks,
Sanders

**Comment by shelleyp** [comment]
Hey Sanders

Yes, I just re-built the JS Cookbook excerpt book for all four formats.

If you look in Chapter 1 for the recipe titled Finding and Highlighting All
Instances of a Pattern, there's a graphic with a list of text resulting
from the application. The image looks fine in the PDF, but there are
distinctive artifacts in the image when I look at it using my Kindle
Preview app for the PC.

It's not bad,and I can live with it, but I do notice a difference in
quality.

Now, could be the application, and if the exact same image is used with
both, then it probably is the app. Leads me to wonder, though, if there
isn't a criteria we should use with images to ensure good results in all
four formats.

Thanks!

Shelley

On Sat, Jul 6, 2013 at 11:01 AM, Sanders Kleinfeld <notifications@github.com

**Comment by sandersk** [comment]
Hi @shelleyp,

I took a look at the two images in the "Finding and Highlighting All Instances of a Pattern" in EPUB, Mobi, and PDF. I'm not seeing any artifacts in the images in Kindle Previewer on my machine, nor am I seeing any issues in PDF or EPUB output, so I think we're fine here (I find Kindle Previewer to be a bit buggy in terms of rendering sometimes, so I wouldn't be overly concerned if there's some oddities).

In general, I think it's best to leave the image processing to the Illustrations team, who will audit all the images when the book comes into Production. They have a series of Photoshop actions that they run in order to ensure that images are optimized for all the ebook outputs, and after that's done, the Production Editor can help you review the ebook files to ensure everything looks good.

Hope this helps,
Sanders
