### ISSUE TITLE
offline_only/online_only vs. Examples

### ISSUE THREAD

**Issue by jdeisenberg** [MakerPress/atlas-public-feedback#287]
See Chapter 1 of SVG Essentials 2e (1234000000446).

The PDF doesn't show text in the form "Example 1-n" in italic before the example title, and the links don't appear to work in the Chimera version. The markup is in this generic format:

```
Sample markup is in <<svgess-CHP-1-EX-7,Example 1-7>>. 
[offline_only]#The result is in <<svgess-CHP-1-FIG-13,Figure 1-13>>.# 

[[svgess-CHP-1-EX-7]]
.This is the example caption

[role="offline_only"]
[source, xml]
----
<svg width="140" height="170">
<!-- lots of XML -->
</svg>
----

[role="offline_only"]
[[svgess-CHP-1-FIG-13]]

[role="offline_only"]
.This is the figure caption
image::images/web/svge.0113.png[]

[role="online_only"]
iframe::http://example.com/ch01/ex01-07.html[width="100%", height="600px"]
```

**Comment by sandersk** [comment]
Hi @jdeisenberg,

Your markup looks good; just a couple small tweaks needed. I went ahead and made the following changes to the markup starting on line 343 of ch01.asciidoc, so you'd have them as a guide moving forward:
- For our toolchain, all formal examples must be delimited as AsciiDoc ExampleBlocks, as follows:

```
[[svgess-CHP-1-EX-7]]
.Paths
====
[role="offline_only"]
[source, xml]
----
<svg width="140" height="170"
<!-- More code here -->
----
====
```
- In order to apply role="online_only" to an iframe, it needs to be in a formal block of some sort, like a sidebar, e.g.:

```
[role="online_only"]
****
iframe::http://example.com/ch01/ex01-07.html[width="100%", height="600px"]
****
```

If you don't want to put them in a sidebar, let me know, and I can suggest some alternatives.
- I moved Figure 1-13 outside the example block (preserving "offline_only") and cleaned up the attribute blocks. It now looks like this:

```
[[svgess-CHP-1-FIG-13]]
[role="offline_only"]
.Stage six -- nose
image::images/web/svge.0113.png[]
```
- Also just a side note that's completely unrelated to the question at hand. We prefer you not hardcode text nodes for your cross-references like this:

```
<<svgess-CHP-1-EX-7,Example 1-7>>
```

Instead, you can use markup like this:

```
<<svgess-CHP-1-EX-7>>
```

With the latter, our toolchain will autogenerate the text "Example 1-7" when the ebook and Web outputs are generated. This is preferable because if at a later point, for example, you swap Example 1-6 and Example 1-7, the numbering will update automatically in your cross-references, and you won't have to worry about editing the markup yourself.

Take a look at the PDF and HTML builds I just did with these changes in place, and let me know how things look, and if you have any questions or need anything further.

Thanks,
Sanders

**Comment by jdeisenberg** [comment]
Thanks for the info. The hardcoded text nodes as in:

```
<<svgess-CHP-1-EX-7,Example 1-7>>
```

are the result of whatever tool converted the first edition (which was written in Docbook) to asciidoc. I'll go through and eliminate them.  I also see remnants of other tools:

```
== Transforming the+++<?lb?>+++ Coordinate System
This technique is akin +++<?troff .ne 10?>+++to constantly
```

The first one appears to be a hard line break; the second seems to be a test for available space. I'm guessing I should remove them. Is that correct?

I want the interactive examples to look like part of the normal flow of the narrative. If a sidebar won't interrupt that visual context, then I'm fine with it. Otherwise, yes, I'd like to know about alternatives.

**Comment by sandersk** [comment]
Hi @jdeisenberg,

Yup, you can remove both the +++<?lb?>+++ and +++<?troff .ne 10?>+++ bits. These are legacy Processing Instructions that we must have had in our XML source; they're not used for anything anymore.

The sidebar markup will put the interactive <iframe>s in a gray box. If you don't want that, what you can do instead is the following passthrough syntax:

```
++++
<para role="online_only">
<?iframe width="100%" height="600px" src="http://langintro.com/svgess2/ch01/ex01-07.html"?>
</para>
++++
```

And the interactive will be part of the same visual flow.

Hope this helps,
Sanders

**Comment by sandersk** [comment]
Either way: you can put the sidebar inside or outside the example block. I'd probably put it outside, so that the example is just the code, but that's just my own organizational preference :)

**Comment by jdeisenberg** [comment]
Just rebuilt the book. The sidebar is definitely not the way to go, because of the color contrast. I also notice that, using Chimera, in the example you changed I see both the source and the iframe; I want to see only the iframe.

**Comment by sandersk** [comment]
Hi @jdeisenberg,

Sorry about both the source and the iframe showing up in the Chimera version. I made some configuration tweaks in our backend to fix that. Take a look at the Web version now, and let me know if it looks OK.

Thanks,
Sanders

**Comment by jdeisenberg** [comment]
Thank you! It looks great. I will get all the examples to have a consistent look when I next have time.
