### ISSUE TITLE
How not to link things that look like email addresses?

### ISSUE THREAD

**Issue by mrichardson23** [MakerPress/atlas-public-feedback#291]
In the asciidoc text below:

```
By default, your BeagleBone identifies itself with the hostname +beaglebone+
on your network so that you can access it via the web with
+http://beaglebone.local+ or SSH with +ssh root@beaglebone.local+.
In most cases, you won't need to change this, but if you start to use
many BeagleBones on the same network, you'll want to distinguish
one from another. 
```

root@beaglebone.local is shown in the PDF as an email address (linked with a mailto: like Github is doing here). I tried [subs="none"] before the block, but then it shows all the + signs as well. How do I get it not to link as though it's an email address?

**Comment by sandersk** [comment]
Hi @mrichardson23,

Try using backticks instead of plus signs to enclose the literal text, like this:

```
`ssh root@beaglebone.local`
```

In AsciiDoc, the backtick delimiters specify an "inline literal passthrough", which ensures that no other substitutions will be done on the content inside. By contrast, plus-sign delimiters allow further substitutions, so AsciiDoc will tag root@beaglebone.local as an email address.

Hope this helps,
Sanders

**Comment by mrichardson23** [comment]
Thanks!
