### ISSUE TITLE
Git clone fatal error

### ISSUE THREAD

**Issue by sarahs** [MakerPress/atlas-public-feedback#298]
One of our indexers gets an error when she tries to clone down this book: http://atlas.labs.oreilly.com/books/1234000001510

I tried it on my end and got the same thing. Any idea what's happening?

```
$ git clone https://sarahs%40oreilly.com@atlas-server.oreilly.com/git/1234000001510.git
Cloning into '1234000001510'...
Password for 'https://sarahs@oreilly.com@atlas-server.oreilly.com': 
remote: Counting objects: 2133, done.
remote: Compressing objects: 100% (2091/2091), done.
fatal: The remote end hung up unexpectedly MiB | 4.61 MiB/s     
fatal: early EOF
fatal: index-pack failed
```

**Comment by sandersk** [comment]
Hi @sarahs,

The problem here is likely that the repo is 858 MB in size, which is going to be too big for us to clone down via Atlas HTTP. Do you think it would be feasible from a workflow standpoint to move this repo to GitHub for the remaining production work? If so, I can help with that.

Thanks,
Sanders

**Comment by sarahs** [comment]
Thanks Sanders. I confirmed with Chris that it's okay to move this one to GitHub. I made the repo here:

https://github.com/oreillymedia/tinkering

But I can't move the files into it from Atlas because I can't clone down that repo. Is that something you can do?

**Comment by sandersk** [comment]
Worked with Sarah to move the book over to GitHub. Should be all set now.
