### ISSUE TITLE
Need a way to generate a PDF with monochrome syntax highlighting..

### ISSUE THREAD

**Issue by swartzrock** [MakerPress/atlas-public-feedback#301]
.. that matches how it will appear in the final printed book, eg using boldface for keywords. 

The current PDF highlighting is too bright, and doesn't serve as a useful preview of the final printed version.

**Comment by sandersk** [comment]
Hi @swartzrock,

The PDF you generate via Atlas is a Web PDF, which represents what we will sell as an ebook. This PDF is not intended for print. We don't currently support grayscale syntax highlighting for one-color print books, so the print version will not have syntax highlighting at all. However, this is something we're evaluating for the future, so we'll keep you posted on that.

Best,
Sanders

**Comment by swartzrock** [comment]
Hi, syntax highlighting can include using boldface for reserved words, so its very doable with monochrome printing.

Is there a way to customize the syntax highlighting for ebooks? The default color scheme is very bright and a bit hard to read.

**Comment by sandersk** [comment]
Hi @swartzrock,

Thanks, yes, we're aware that syntax highlighting is doable for one-color printing, but are currently doing some evaluation and testing around how best to implement it in our print templates. We will definitely let authors know when that functionality is available.

Regarding syntax highlighting for ebooks, we use the same color scheme across all O'Reilly ebooks in order to give our customers a consistent experience (e.g., strings are always in orange), and do not permit customizations on a book-by-book basis unless there is a compelling argument for it. But I will pass along your feedback regarding brightness to our designers, as we regularly review our specs based on author/customer feedback.

Sanders

**Comment by swartzrock** [comment]
Fair enough, thanks!
