### ISSUE TITLE
Is Atlas down?

### ISSUE THREAD

**Issue by myarbrough** [MakerPress/atlas-public-feedback#303]
Atlas works to access my projects, and the Dashboard of the book I'm trying to access (High Performance Browser Networking), but when I select a specific chapter, I get a 500 error. 

http://atlas.labs.oreilly.com/books/1230000000545/versions/master/editor/p1-ch01.asciidoc

Thanks!
Mel

**Comment by jhosman** [comment]
Spoke with Mel and she's no longer having this access problem. Closing out ticket.

**Comment by adamwitwer** [comment]
Yeah, I fixed it. :-) The files were encoded as Latin-1 instead of UTF-8, which created encoding errors for some special characters (en and em dashes, specifically). I reencoded the files to UTF-8 and fixed the corrupt en and em dashes.

The builds are still failing, though. See: http://atlas.labs.oreilly.com/books/137/jobs/36945. But that's not related to the encoding problems.

**Comment by jhosman** [comment]
Thanks @adamwitwer. Sorry I robbed you of the fun of clicking "Close."

**Comment by adamwitwer** [comment]
Ha! No worries, I should've told you we were looking at it!
