### ISSUE TITLE
chimera.labs.oreilly.com auth seems to have died

### ISSUE THREAD

**Issue by simonstl** [MakerPress/atlas-public-feedback#306]
At least it just sits there forever with the clock thing rotating.  I've tried a few times this morning to no effect.

**Comment by sandersk** [comment]
Hi Simon,

Thanks for the report. Heroku is having some serious latency issues with their servers right now, so that's likely the cause of the problems you're experiencing with Chimera. We believe this problem should resolve itself when Heroku gets back up and running normally, and will keep an eye on things to confirm.

Sanders

**Comment by sandersk** [comment]
Hi Simon,

Things should be back up and running now. Can you let us know if you're still having problems authenticating on chimera.labs.oreilly.com, and if so, what browser/version you're using?

Thanks,
Sanders
