### ISSUE TITLE
AsciiDoc Table Problem

### ISSUE THREAD

**Issue by mrichardson23** [MakerPress/atlas-public-feedback#313]
I'm having trouble with this Asciidoc table:

```
[[ch03-comparison-operators]]
.Comparison Operators
[options="header"]
|=======================
|Operator|Meaning
|x == y|x is equal to y
|x != y|x is not equal to y
|x <  y|x is less than y
|x >  y|x is greater than y
|x <= y|x is less than or equal to y
|x >= y|x is greater than or equal to y
|=======================
```

When I build, I get the error: "asciidoc: ERROR: ch03.asciidoc: line 357: [tabledef-default] missing style: y*" a bunch of times.

I've tried using a backslash to escape the < and the = characters, but that didn't seem to do it.

**Comment by sandersk** [comment]
Hi @mrichardson23,

In this case, it's actually the "y" characters that need to be escaped, because by default, AsciiDoc will interpret a single letter preceded by a space and directly followed by a cell delimiter (|) as a style parameter (http://www.methods.co.nz/asciidoc/userguide.html#X71) rather than text that should be processed for output.

Escaping the "y"s with a backslash won't work, because the backslash will also be passed on to the output, but you can use the double-dollar passthrough ($$) to get the results you want. If you revise the markup as follows (surrounding the "y"s at the end of each cell in the first column with $$):

```
[[ch03-comparison-operators]]
.Comparison Operators
[options="header"]
|=======================
|Operator|Meaning
|x == $$y$$|x is equal to y
|x != $$y$$|x is not equal to y
|x < $$y$$|x is less than y
|x >  $$y$$|x is greater than y
|x <= $$y$$|x is less than or equal to y
|x >= $$y$$|x is greater than or equal to y
|=======================
```

You should get the output you want. Give it a try and let me know if you encounter further issues, or have additional questions.

Thanks,
Sanders

**Comment by mrichardson23** [comment]
Thanks. That did the trick.
