### ISSUE TITLE
Possible to eliminate build commits, so authors don't have to "git pull"?

### ISSUE THREAD

**Issue by sandersk** [MakerPress/atlas-public-feedback#32]
Don't see a preexisting issue for this, although I'm pretty sure we've gotten this feedback before.

Tim Berglund from GitHub suggested the following to Adam via email:

"I would definitely suggest that the build system not generate new commits. It would be cleaner if commits only came from editing activities in the UI or edits on my local clone that I push up to the repo. If you make commits after you build, I'm always having to pull from the source, which doesn't quite make sense."

**Comment by MakerPress** [comment]
Yes, this is something of a pain that can be fixed by putting "book.asciidoc" in your .gitignore file.  It mostly affects only git power-users.

I think we want to keep the commit, though, so that we can keep the build persistent.  

Andrew

----- Original Message -----
From: Sanders Kleinfeld reply@reply.github.com
To: MakerPress makerpressadmin@oreilly.com
Sent: Mon, 23 Jul 2012 09:45:28 -0400 (EDT)
Subject: [atlas-public-feedback] Possible to eliminate build commits, so authors don't have to "git pull"? (#32)

Don't see a preexisting issue for this, although I'm pretty sure we've gotten this feedback before.

Tim Berglund from GitHub suggested the following to Adam via email:

"I would definitely suggest that the build system not generate new commits. It would be cleaner if commits only came from editing activities in the UI or edits on my local clone that I push up to the repo. If you make commits after you build, I'm always having to pull from the source, which doesn't quite make sense."

---

Reply to this email directly or view it on GitHub:
https://github.com/MakerPress/atlas-public-feedback/issues/32

## 

Andrew Odewahn
Chief Technology Officer
O'Reilly Media
617-460-6693

**Comment by runemadsen** [comment]
The reason why building a book triggers a commit is that we are writing the
new build order into book.asciidoc. The problem with not doing this is that
we need to preserve the state of the build so it's reflected on the worker
server. We found that the easiest way to do this is to just have a
book.asciidoc in the repo folder.

I guess I see this more of a feature than a bug. If it get too annoying to
`git pull` then we should change it. One simple thing we could do would be
to not commit anything into the repo if the build order did not change.

On Mon, Jul 23, 2012 at 9:45 AM, Sanders Kleinfeld <
reply@reply.github.com

**Comment by adamwitwer** [comment]
Rune resolved this today!
