### ISSUE TITLE
Issues with PDF build

### ISSUE THREAD

**Issue by bandersonoreilly** [MakerPress/atlas-public-feedback#326]
I've got some errors with a build.

project is: http://ano-atlas2.herokuapp.com/books/1234000001926

Errors below:

---

Job failed
Full error:

asciidoc: WARNING: book.asciidoc: line 3: {include:/usr/local/app/worker/tmp/pdf/1234000001926/book-docinfo.xml}: file does not exist
asciidoc: ERROR: Chapter-1.asciidoc: line 37: [tabledef-default] total width less than 100%: 0
asciidoc: ERROR: Chapter-1.asciidoc: line 37: [tabledef-default] missing leading separator: (?msu)((?<!\S)((?P<span>[\d.]+)(?P<op>[_+]))?(?P<align>[<^>.]{,3})?(?P<style>[a-z])?)?|
asciidoc: WARNING: Chapter-1.asciidoc: line 127: section title out of sequence: expected level 3, got level 4
asciidoc: ERROR: P-REST.asciidoc: line 13: [tabledef-default] missing closing delimiter
asciidoc: ERROR: P-REST.asciidoc: line 13: [tabledef-default] total width less than 100%: 0
asciidoc: ERROR: P-REST.asciidoc: line 13: [tabledef-default] missing leading separator: (?msu)((?<!\S)((?P<span>[\d.]+)(?P<op>[_+]))?(?P<align>[<^>.]{,3})?(?P<style>[a-z])?)?|

**Comment by sarahs** [comment]
Hi Brian. Looks like some markup problems are causing the errors:
- A few tables in Chapter-1.asciidoc and P-REST.asciidoc have `[=======` instead of `|=======`. See for example the table titled "HTTP Verbs." Just change the `[` to `|`.
- In Chapter-1.asciidoc, the last section "Conclusion" has `-------` underneath it, but that's the style for a chapter title. It should probably be a sect1, which would be `~~~~~~` instead. Same goes for "Server-Side Cache Headers" in P-Caching.asciidoc.
- In P-Caching.asciidoc, the last code block has only three `---` at top and bottom when it should have four `----`.

Fixing these things should get rid of the build errors. One other thing I noticed is the `[NOTE]` markup in P-REST.asciidoc needs `====` above and below the text (see http://chimera.labs.oreilly.com/books/1230000000065/ch04.html#Admonitions).

**Comment by bandersonoreilly** [comment]
Thank you Sarah; I'll have the author make the changes.
