### ISSUE TITLE
Suggestion: "Draft" option -> build date/time stamp in book

### ISSUE THREAD

**Issue by ghost** [MakerPress/atlas-public-feedback#333]
I often find myself looking at two different builds of the book, and it would be convenient to have a timestamp in them to see when they were built. But even with one, it would be handy to have a timestamp to be sure you remembered to download the latest version after a run of several experimental builds.

This could be a permanent feature, on the front matter page. While I submit that that would be a useful addition to the build process, Editorial may not be ready for it.
Thus, it could for now be a feature one had to ask for with a checkbox on the build page.

Indeed, there could be a permanent one-liner there, and have the checkbox enable additional build information, like, for instance, the Git revision.

**Comment by sandersk** [comment]
Hi @androidcook,

Thanks for this great suggestion, as well as all the other great feedback from this past weekend. We're actually hard at work right now at the next release of Atlas, so we're now in the process of reviewing and prioritizing all the feature requests we get. We will keep you posted.

The new version of Atlas (coming in 2014) will have a build page that lets you access the most recent builds you've performed, with timestamps indicating when they were triggered. I also like your suggestion of embedding the timestamp and/or additional metadata directly in the output files, so that's something we'll consider as well.

Best,
Sanders
