### ISSUE TITLE
Build errors (with included JS files)

### ISSUE THREAD

**Issue by bandersonoreilly** [MakerPress/atlas-public-feedback#335]
I've got a few errors (having to do with callouts and list items with included files) that I can't seem to fix.

Book:
http://ano-atlas2.herokuapp.com/books/1234000000310

Error message:
http://ano-atlas2.herokuapp.com/books/344/jobs/45620

**Comment by sandersk** [comment]
Hi @bandersonoreilly,

The issue is with the markup in the CONTRIBUTING.md file. Since it appears just to be a placeholder for now, I removed it from the book builds, and that took care of the errors.

If the CONTRIBUTING.md content is going to be added to the book later on, I'd suggest switching to AsciiDoc from Markdown, if feasible, as having all the files in one format would make the content easier to manage and troubleshoot down the road.

Let me know if you hit any further issues.

Thanks,
Sanders

**Comment by bandersonoreilly** [comment]
Great, thank you Sanders!
