### ISSUE TITLE
Book build is stuck on older version, will build but without any of the changes

### ISSUE THREAD

**Issue by aantonop** [MakerPress/atlas-public-feedback#338]
I'm trying to build 

https://ano-atlas2.herokuapp.com/books/1234000001802

It creates PDF but it only contains older content. I have changed the content in Chapter 2 completely and it does not appear. Instead it includes all the chapters (stubs) that I have since removed from the build page. It's like it is not generating a new PDF. 

I am also trying to find the build output for each job so that I can troubleshoot it myself more effectively. I saw other authors here refer to a job URL which has the build output. How do I find those pages for my book?

Thanks

**Comment by sandersk** [comment]
Hi @aantonop,

Are you still seeing an old PDF when you build? I took a look at the latest PDF you built (7 days ago), and it includes only Chapters 1 and 2. 

I suspect your browser may have cached an older PDF, and that that's why what you're seeing is out of date. If you're still seeing an old PDF, could you try clicking Refresh in the browser after loading the PDF (or just try loading the PDF in a different browser)? Let me know if you still encounter issues.

In terms of locating job URLs, those are only generated for builds that fail. For failing builds (those highlighted in red), if you click the "See full error" link, you'll be taken to a page describing the error, which is at a permanent URL in the form:

http://atlas.labs.oreilly.com/books/<number>/jobs/<number>

Hope this helps,
Sanders
