### ISSUE TITLE
Error logs are much less useful if we don't have the "tmp/.../book.xml" file

### ISSUE THREAD

**Issue by deanwampler** [MakerPress/atlas-public-feedback#346]
An example from a recent failure:

```
DCPS Error Log

/usr/local/app/worker/tmp/epub/1234000001978/book.xml
== Error 1

/usr/local/app/worker/tmp/epub/1234000001978/book.xml:491: parser error : Opening and ending tag mismatch: programlisting line 417 and sect2

----
</sect2>
```

Since I don't have the generated book.xml, it's rather difficult to see what's really wrong. Are they accessible?

**Comment by sandersk** [comment]
Hi @deanwampler,

Unfortunately, we don't make the generated book.xml accessible back to Atlas users at this time. I realize this makes troubleshooting errors more challenging, as you need to infer based on context what the issue is with the AsciiDoc. If you encounter any error messages for which it's not readily apparent what's wrong, please feel free to make a ticket, and the tools team will take a look.

Just to give you an idea where we're heading long-term, we're overhauling our AsciiDoc infrastructure for the next release of Atlas (which will most likely be out ~February), and this release will include both more robust error handling and enhanced error reporting for troubleshooting purposes. So improving this aspect of Atlas is definitely on our short-term roadmap.

Sorry for any inconvenience and thanks for your patience,
Sanders
