### ISSUE TITLE
Multi-paragrph variable lists disruped by paragraph id tags

### ISSUE THREAD

**Issue by deanwampler** [MakerPress/atlas-public-feedback#353]
I have a variable list near the beginning of the section "Introducing Scala" in chapter 2 of my book (ch02-WhyScala.asciidoc) that looks something like this:

```
Mixed paradigm—object-oriented programming:: Scala fully supports _object-oriented programming_ (OOP).  ...can also be implementated.((("object-oriented programming (OOP)", "mixed paradigm in Scala")))((("mixin composition")))((("traits")))
+
In Scala, everything is ... is needed.((("FP", see="functional programming")))
```

This entry, the second in the list, has two paragraphs. For a while it didn't render correctly, the second paragraph had the normal paragraph formatting, i.e., not indented and a "+" in front of it. Several other entries had this problem.

I noticed that they had paragraph id tags on the line before the "+" lines, e.g., "[[para_somethin_or_other]]. When I removed the tags, the lists formatted correctly.

**Comment by sandersk** [comment]
Hi @deanwampler,

Good catch. Yes, the proper markup in this case is for the id tag to follow the + line, not precede it. In other words, it should look like this:

```
Mixed paradigm—object-oriented programming:: Scala fully supports _object-oriented programming_ (OOP).  ...can also be implementated.((("object-oriented programming (OOP)", "mixed paradigm in Scala")))((("mixin composition")))((("traits")))
+
[[para_somethin_or_other]]
In Scala, everything is ... is needed.((("FP", see="functional programming")))
```

Since we're the ones that converted the 1st edition's DocBook source files to AsciiDoc for you, I'm assuming the issues with the misplaced id tags here are a result of a bug in our converter. I'll make a ticket for our Tools team to  investigate this.

If you notice that this issue is more widespread throughout the book (and not just limited to a few variable list terms), and you'd like assistance with further cleanup, let us know, and we'd be happy to help out with that.

Apologies for any inconvenience here,
Sanders
