### ISSUE TITLE
Another build issue I can't figure out

### ISSUE THREAD

**Issue by bandersonoreilly** [MakerPress/atlas-public-feedback#354]
Book:
http://ano-atlas2.herokuapp.com/books/1234000001926

Error:
http://ano-atlas2.herokuapp.com/books/946/jobs/48012
# Error text:

Job failed
Full error:

DCPS Error Log

/usr/local/app/worker/tmp/pdf/1234000001926/book.xml
== Error 1

/usr/local/app/worker/tmp/pdf/1234000001926/book.xml:310: parser error : Opening and ending tag mismatch: sect2 line 300 and programlisting

---

---</programlisting>

---

== Error 4

/usr/local/app/worker/tmp/pdf/1234000001926/book.xml:311: parser error : Opening and ending tag mismatch: sect1 line 273 and sect2

---

</sect2>

---

== Error 7

/usr/local/app/worker/tmp/pdf/1234000001926/book.xml:359: parser error : Opening and ending tag mismatch: sect2 line 312 and programlisting

---

Content-Type: application/x-www-form-urlencoded</programlisting>

---

== Error 10

/usr/local/app/worker/tmp/pdf/1234000001926/book.xml:364: parser error : Opening and ending tag mismatch: chapter line 267 and sect2

---

</sect2>

---

== Error 13

/usr/local/app/worker/tmp/pdf/1234000001926/book.xml:374: parser error : Opening and ending tag mismatch: sect2 line 365 and programlisting

---

Content-Type: application/json</programlisting>

---

== Error 16

/usr/local/app/worker/tmp/pdf/1234000001926/book.xml:377: parser error : Opening and ending tag mismatch: book line 6 and sect2

---

</sect2>

---

== Error 19

/usr/local/app/worker/tmp/pdf/1234000001926/book.xml:378: parser error : Extra content at the end of the document

---

<sect2 id="_afpropertylistrequestserializer">

---

**Comment by chrishearse** [comment]
Hi Brian!  

It looks like there were just a few issues:

Introduction.asciidoc was missing a section 1 heading.  Currently the document contains at the top:

## Introduction

Why I Wrote This Book
^^^^^^^^^^^^^^^^^^^^^

Instead it should have the two "="s so it should be like this next to "Introduction":

## == Introduction

Why I Wrote This Book
^^^^^^^^^^^^^^^^^^^^^

Also, even though Chapter-2.asciidoc doesn't have much, it should also have the "=" markup so it should look like this:

## == Chapter 2: Request Operations

Lastly, in Chapter-5.asciidoc you should see that the code right after "...capable of efficiently streaming files on disk or in-memory data." only has three "-" symbols on both sides:

[source,objective-c]
---
NSString *URLString = @"http://example.com";
NSDictionary *parameters = @{@"foo": @"bar", @"baz": @[@1, @2, @3]};

NSURLRequest *request = [[AFHTTPRequestSerializer serializer] requestWithMethod:@"GET" URLString:URLString parameters:parameters];
---

It should have four on both sides of the code ("----") instead of three. Same for the code right below it as well.  Once all three of those are fixed the pdf should generate.You can also refer to http://chimera.labs.oreilly.com/books/1230000000065/index.html for the appropriate AsciiDoc markup to authors.  

-Chris

**Comment by bandersonoreilly** [comment]
Thank you, Chris, I've forwarded this information to the author. I'll let you know if we have any follow up questions.
