### ISSUE TITLE
duplicate callout numbers in numbered list 

### ISSUE THREAD

**Issue by ramalho** [MakerPress/atlas-public-feedback#358]
I have a asciidoc code and a PDF to show this issue, but they belong to an unpublished manuscript. Where should I send the samples?
![callout-bug-1](https://f.cloud.github.com/assets/29944/2030011/f118c5c8-88ef-11e3-80ad-65ae8ecac80d.png)

I don't know if this is related to the bug, but I inserted the callouts in the order <1>, <3> and <3> in the code listing, on purpose, because I wanted to discuss the middle section of the code after. The numbering I used was ignored by Atlas, resulting in a mismatch of the callout numbering in the explanations.

**Comment by zaremba** [comment]
Hi @ramalho, sorry for the delayed response here. Are you still experiencing duplicate callout numbers?

**Comment by zaremba** [comment]
http://atlas.labs.oreilly.com/books/1234000001884/versions/master/editor/From-iterables-to-generators.asciidoc

**Comment by christopappas** [comment]
Hi @ramalho,

The duplicate callouts in the pdf are being caused by comments in a linked python code example that are signaling for callouts, but no callout syntax is used after the example in the asciidoc. This essentially leaves some callouts hanging in limbo and they end up getting tacked on to the next example of the book.

Specifically, in the code example code/sequences/sentence.py, there are comments (`# <1> # <2> # <3>`) that signal callouts, but after its appearance in Creating-sequence-types.asciidoc, no callouts are placed in the asciidoc text. The next code example in the book that uses callouts is the first example in From-iterables-to-generators.asciidoc (coincidentally code/sequences/sentence.py again), and this is where we see the duplication happen.

To solve this problem, you can add callout syntax in Creating-sequence-types.asciidoc after the code/sequences/sentence.py example.  Note that if you take out the callout syntax in the python code's comments, the duplicate callouts will also disappear, but because the code example is used more than once, the instance of code/sequences/sentence.py in From-iterables-to-generators.asciidoc would also lose its callouts.

Hope this helps,
Chris
