### ISSUE TITLE
snippets not working -- get alternative text

### ISSUE THREAD

**Issue by MarcRochkind** [MakerPress/atlas-public-feedback#362]
In my .asciidoc file I have this:

```
[filename="code/02-developing/Debug1/debug1.js", language="js", identifier="LOGEXAMPLE1"]
snippet~~~~
Put any descriptive text you want here. It will be replaced with the
specified code snippet when you build ebook outputs
snippet~~~~

----
include::code/02-developing/Debug1/debug1.js[tabsize=4]
----
```

The "include" works, and shows that the path is OK. In the file debug1.js I have this:

```
window.onload = function () {
    document.getElementById("btn").addEventListener('click', run);
}

// BEGIN LOGEXAMPLE1
function logExample1() {
    console.log(document.body);
    console.dir(document.body);
}
// END

function logExample2() {
    console.error('An error occurred');
}
```

However, I never get the snippet. Only the alternative text.

The book is "Programming Chrome Apps".

**Comment by sandersk** [comment]
Hi @MarcRochkind,

The closing comment delimiter in your code listing should look like this:

```
// END LOGEXAMPLE1
```

Rather than just "// END". If you fix that, the snippet should be sourced in properly.

Apologies if that was unclear from the documentation.

Let us know if you encounter any further issues.

Thanks,
Sanders

**Comment by MarcRochkind** [comment]
That's is... thanks! Docs are OK. I misread them.
