### ISSUE TITLE
Preview Index File

### ISSUE THREAD

**Issue by aplimpton** [MakerPress/atlas-public-feedback#366]
Hello,

I have followed the guide to create an index page and added tags. How do I preview the index to be sure it looks correct?

**Comment by sandersk** [comment]
Hi @aplimpton,

You're referring to the index page for the Web version of the book, correct? Could you point us to the URL of the project you're working on, so we can advise further?

Thanks,
Sanders

**Comment by aplimpton** [comment]
Hi @sandersk,

Thank you for the followup (on a Sat even!) :) For the link it is : http://atlas.labs.oreilly.com/books/1234000002024

The guide (http://chimera.labs.oreilly.com/books/1230000000065/index.html) says "To include an index in your book, first create a blank index.asciidoc file... "  When you say "Web version of the book" do you mean the electronic formats that it can published as (epub etc al) or something else?

Thank you,
Amanda

**Comment by sandersk** [comment]
Hi Amanda,

Thanks for the additional info. Sorry, I had misunderstood you originally and thought you were referring  to an index.html file (e.g., a web homepage), rather than an Index for the book. To preview your index, all you should need to do is add the index.asciidoc file to your Files to Build list, and then any index tags that you added to the book content should be added to the Index page in your PDF, EPUB, or Mobi.

That said, for O'Reilly titles, typically indexing is formally done by a freelance indexer once the book enters Production, so if you haven't done so already, you may want to check with your editor on how the index will be handled for your book.

Let us know if you have any further questions.

Thanks,
Sanders
