### ISSUE TITLE
Part number in TOC resets to Part 1

### ISSUE THREAD

**Issue by otherjon** [MakerPress/atlas-public-feedback#369]
I've generated a PDF for my book, and the PDF's index (the viewer's separate pane of bookmarks, not "index" as in "the last pages of the book") is numbered correctly ("Part 1", "Part 2", "Part 3", etc.), but the table of contents labels each part as "Part 1".

Chapter numbers for each "Part 1" reset to "Chapter 1" and increase normally from there, until they are reset by the beginning of the next part.

**Comment by sandersk** [comment]
Hi @otherjonvb,

Thanks for the bug report. Could you give us the URL of the project you're working on? That will be helpful context in debugging.

Thanks,
Sanders

**Comment by otherjon** [comment]
The project URL is http://ano-atlas2.herokuapp.com/books/1234000002024

Thanks,
Jon

**Comment by sandersk** [comment]
Hi Jon,

Thanks. I took a look, and the issue was that the book was being built in the wrong template, which doesn't have full handling for Parts. I switched to our Animal template (which is the design your book uses), and the Parts are now labeling correctly in the TOC. 

I believe you should be all set now, but let me know if you encounter further issues.

Thanks,
Sanders
