### ISSUE TITLE
Question: How do you store comments made in Chimera?

### ISSUE THREAD

**Issue by markgrover** [MakerPress/atlas-public-feedback#377]
Hi, we have a use-case where we often copy some paragraphs from one place to another. Think of it like having a "staging" copy of the book somewhere and moving paragraphs to a "production" copy of the book when we feel that the paragraph is good enough.

Now, what we have noticed is that when we promote the paragraph from "staging" to "production", we sometimes lose the comments made on the "staging" paragraph. However, we want the comments to stick around.

Now, there are 2 ways that I think we can possibly fix this. I would, however, love to hear if you folks have any other ideas!
1. We somehow find a way to preserve comments across copies. In such a case, it would be great to know how/where Chimera stores comments and if there are some annotations/hints we can use to preserve comments.
2. Thinking more about this, the reason we lose comments is because we have our book.asciidoc points to the "production" copy of the paragraph when when the paragraph is production ready. What could work for us is if we had book.asciidoc pointing to "production" copy but staging_book.asciidoc (or book_in_development.asciidoc) up on chimera too where we could review things and have comments on Chimera. We can then migrate things to "production" but all the comments would exist on the "staging" book on Chimera. Does Atlast/Chimera have functionality to build/host multiple books from the same repo?

Thanks in advance! And, please let me know if you have any better suggestions on how we could do this.

**Comment by sandersk** [comment]
Hi @markgrover,

Yes, the challenge of attaching comments to paragraphs when the manuscript is in draft state is that the paragraphs are mutable, and may be modified significantly, deleted, etc. We're actually working right now on a brand-new collaboration interface for Atlas that will improve the UI around adding comments and tracking changes, which will be released later this year.

But for now, our current algorithm for attaching comments to paragraphs is based on generating a unique id for each paragraph based on the first 15 characters of text in it. If the paragraph is deleted, or its initial text changes significantly, then the comment may become "detached" and no longer show up in the correct spot in Chimera/Atlas.

With respect to your second idea, we don't support building multiple books from the same repo. Because we're using Git for version control, you can have multiple branches of a repo, but builds can only be done off of master, so I'm not sure that's going to meet your needs here. 

One thing that might work here is having two separate projects in Atlas, one for Staging and one for Production, and then you can build the Staging project to Chimera to maintain the comments, while working on the Production project to continue to develop the content. You could use git push/pull commands to merge content between the two projects as necessary.

If you do go this route, please make sure to name each project in Atlas such that it's clear which one is Staging and which one contains the Production-ready content so that there's no confusion for our Editorial and Production teams.

Let us know if you have any questions or if we can be of further help.

Thanks,
Sanders

**Comment by markgrover** [comment]
Thanks for your insight, @sandersk Much appreciated!
