### ISSUE TITLE
Formatted pages only have one line

### ISSUE THREAD

**Issue by MikeW50** [MakerPress/atlas-public-feedback#379]
In the book http://ano-atlas2.herokuapp.com/books/1234000001734, the pages in Chapter 2 and Chapter 3 are being rendered with very little on each page, often a single line. How can I clean up the chapters while still using [role="fullpage"] to force images, tables and sidebars that would otherwise bee too small to span two columns?

**Comment by chrishearse** [comment]
Hi Mike,

It's a tricky one.  It seems like the best solution is to switch out certain elements.  I think the problems in chapter 2 were occurring because it was trying to fit so many elements onto one page.

In chapter 2, if you try putting "How Safe is Model Rocketry" after 

.The author prepares a J rocket for flight.
image::images/Fig%202-14.jpg[]

and build a PDF you'll find that it actually pushes a lot of the content back to around the location of where you wanted it.  I think that should fix the many page issue there.

For Chapter 3 you can do:

 [role="fullpage"]
This rocket is a workhorse, easy to build but very stable. It's also capable of 
reaching altitudes of 1500 feet—over a quarter of a mile!

++++
<?hard-pagebreak?>
++++

[role="fullpage"]
.What's in a Name?

---

Names for rockets, both model....

and I think that should fix it. You also might take off the role="fullpage" from the table. "Tools and Supplies".   It is certainly an odd bug that the pages behave weirdly with certain roles attached.

Hopefully that helps.

Chris
