### ISSUE TITLE
PDF builds but ePub and Mobi do not

### ISSUE THREAD

**Issue by andyoram** [MakerPress/atlas-public-feedback#381]
This particular problem is with Introducing Python, 1234000000574. The ePub and Mobi builds fail with several messages like this:

ERROR Unable to highlight code with language attr shell: global name 'ClassNotFound' is not defined

Needless, to say, ClassNotFound is not in the draft. This looks like an internal error, particularly since the PDF builds without error.

**Comment by sandersk** [comment]
Hi Andy,

Yes, the issue here was the image with the filename `O'Reilly_logo.png`. The toolchain was not properly escaping the single quote, which was causing the error. The most expedient solution here was just to drop the single quote from the filename and the corresponding fileref in the source, so I went ahead and took care of that. EPUB and MOBI are now building successfully.

Sanders

**Comment by andyoram** [comment]
Thanks for the explanation. I'll try to avoid triggering the problem 
in the future. 

Andy 

----- Original Message -----
