### ISSUE TITLE
Book build fails

### ISSUE THREAD

**Issue by bmeike** [MakerPress/atlas-public-feedback#392]
I can't build our book, anymore.  Apparently the definition of &rsquo is missing?

Traceback (most recent call last):
  File "/usr/local/app/worker/.local/bin/db_to_epub", line 138, in <module>
    sys.exit(main())
  File "/usr/local/app/worker/.local/bin/db_to_epub", line 134, in main
    raise e
lxml.etree.XMLSyntaxError: Entity 'rsquo' not defined, line 10, column 261

**Comment by bmeike** [comment]
btw, is there anything we can do so that that error message is even slightly useful?  "line 10" in what?

**Comment by sarahs** [comment]
Hi @bmeike,

Can you point me to the Atlas project you're working on? I see Programming Android 3E here:

http://atlas.labs.oreilly.com/books/1234000001907

but it looks like all formats have successfully been generated as of 15 hours ago. Does that mean you were able to solve the build problem, or are you referring to a different project?

Thanks,
Sarah

**Comment by bmeike** [comment]
Hi Sarah,
  You have the right project. Yes, it compiles.  It just doesn't work.  ;-)

Here are the problems of which I am aware:

1) Substantial parts of the source were converted by using aciidoc literal "++++" around docbook code.  That is incredibly fragile and breaks if you move it around.  In particular there were lots of <sect4> s.  I may have fixed that.

2) The book.asciidoc file is hacked like crazy to get the build to complete.  What I did in there definitely won't work for real.

3) We are missing sections

4) We are missing a ToC

5) I commented out the "[[prolog]]" tag because it caused an error.

-blake

**Comment by sarahs** [comment]
Hm, the first thing I notice is there is a book.xml file along with the AsciiDoc files. The way Atlas works, if it sees a book.xml file, it will try to build from that before it looks for a book.asciidoc.

Where did that book.xml come from? It has `<article>` root tags instead of `<book>`, among other markup that will not work with the Atlas toolchain. If you can simply delete book.xml from the project, the book.asciidoc is all you need. 

Additionally, I noticed an issue in ch15 with this markup:

```
++$$KEYCODE_+++<?lb?>+++CAMERA$$++
```

Our toolchain also doesn't support the `<?lb?>` processing instruction. If you're just trying to get those two parts of the term to break properly across a line, you might try this instead:

```
pass:[<literal role="keep-together">KEYCODE_</literal><literal role="keep-together">CAMERA</literal>]
```

If you fix the above and remove the book.xml, I believe your builds should start working, but please let me know if not and I'll take another look.

Thanks,
Sarah

**Comment by bmeike** [comment]
On May 5, 2014, at 12:16 PM, sarahs notifications@github.com wrote:

> Hm, the first thing I notice is there is a book.xml file along with the AsciiDoc files. The way Atlas works, if it sees a book.xml file, it will try to build from that before it looks for a book.asciidoc.
> 
> Where did that book.xml come from?
> 
> No idea.  It was there when we got there.
> It has <article> root tags instead of <book>, among other markup that will not work with the Atlas toolchain. If you can simply delete book.xml from the project, the book.asciidoc is all you need.
> 
> I think what we are asking is if someone would, please, import the book correctly.  We have worked on the previous 2 editions of this book, using DocBook.  The idea of spending a week or two or so figuring out all of this stuff, so that we can use Atlas, seems like time ill spent.

I would prefer to use DocBook.  If, however, we can get a working version of our book, in Atlas, without to much more trouble, we can all learn asciidoc.  For us to go through debugging the import, however, seems, as I said, misdirected energy.

> Additionally, I noticed an issue in ch15 with this markup:
> 
> ++$$KEYCODE_+++<?lb?>+++CAMERA$$++
> Our toolchain also doesn't support the <?lb?> processing instruction.

Interesting.  So why'd the import put them there?

> If you're just trying to get those two parts of the term to break properly across a line, you might try this instead:
> 
> pass:[<literal role="keep-together">KEYCODE_</literal><literal role="keep-together">CAMERA</literal>]
> If you fix the above and remove the book.xml, I believe your builds should start working, but please let me know if not and I'll take another look.
> 
> I'll give that a try.

-blake

**Comment by bmeike** [comment]
I've made the suggested changes and they have not resulted in a buildable source.

I’d like to get this issue resolved, this week.  I don’t want to do more work in a format that isn’t going to work, in the long run.

If we don’t have a clear way to a reliable, working Atlas version of this book, by Friday, I will spend the weekend back porting Zigurd’s work into the DocBook version of the 2nd edition, so that we can move forward there.

Here are the outstanding issues, that I see:

1) Substantial parts of the source were converted by using aciidoc literal "++++" around docbook code.  That is incredibly fragile and breaks if you move it around.  In particular there were lots of <sect4> s.  I may have fixed that.

2) The book.asciidoc file is hacked like crazy to get the build to complete.  What I did in there definitely won't work for real.

3) We are missing sections

4) I commented out the "[[prolog]]" tag because it caused an error.

-blake

**Comment by sarahs** [comment]
My apologies that you've run into trouble here. We want you to be able to use our tools to build your book as easily as possible so you can focus on writing, not on debugging build errors. I realize that's frustrating.

Regarding the import issues, the DocBook->AsciiDoc conversion was originally done by a colleague (who is no longer here) about eight months ago, so I'm tracing back her work. She did send information about the passthrough ++++ markup in an email to Zigurd back on October 3, and explained that this type of conversion is inherently difficult because highly semantic XML markup is being converted to lighter-weight AsciiDoc markup, which can occasionally lead to issues in the output. For example, the reason the sect4s are converted to passthroughs is that AsciiDoc has no native markup for sect4.

That said, options from here:
- If you would prefer to work in DocBook, I'd be happy to put it back in that format for you. I can start working on that immediately. You can then work with the files locally using any kind of XML editor you'd like, and just push to Atlas in order to build. If you maintain valid DocBook, your builds should go through smoothly.
- If you want to try to continue with AsciiDoc, I will look into the remaining errors related to the Mobi/EPUB/HTML builds and attempt to get it all working as soon as possible.

Thanks for your patience,
Sarah

**Comment by bmeike** [comment]
On May 6, 2014, at 8:35 AM, sarahs notifications@github.com wrote:

> email to Zigurd back on October 3
> 
> Ahh.  Didn't see it.
> For example, the reason the sect4s are converted to passthroughs is that AsciiDoc has no native markup for sect4.
> 
> I've converted all the <sect4>s into <section>s.  I hope that works.
> That said, options from here:

Polling the other authors.  Should have an answer by eow

-blake

**Comment by bmeike** [comment]
I discussed the problem with Blake. Blake finds working in docbook
acceptable, but I found wasted a lot of my time trying to fix syntax errors
with uninformative error messages. I was getting better at it, but it's not
a learning curve I want to climb again.

asciidoc is not much better, especially since it compiles to xml. That
invites half-measures, like converting the Programming Android manuscript
with lots of quoted docbook in it. This is a really bad state to be in
since the manipulations we made to move parts of the manuscript around to
reflect our revised ToC are completely legit in the asciidoc editor. I made
no attempt to "go around" the editor, and yet the book build is fubar.

I think what we need from O'Reilly's tools people is a "clean" conversion
to asciidoc, with no legacy of the previous use of docbook. I'd wager it
will be much harder to break the book build if there is no hidden docbook
in the manuscript and we start with good asciidoc formatting practices.

We don't have complex formatting needs. To realize the advantages of
simplicity we need a clean manuscript. But, with Blake producing a lot of
new writing, we need it quick.

Is what I'm asking for do-able, and by when?

Regards,
Zigurd

**Comment by bmeike** [comment]
Ally, wanted to be sure this reached you.
-AJ

On Mon, May 5, 2014 at 5:44 PM, Blake Meike blake.meike@gmail.com wrote:

> On May 5, 2014, at 12:16 PM, sarahs notifications@github.com wrote:
> 
> Hm, the first thing I notice is there is a book.xml file along with the
> AsciiDoc files. The way Atlas works, if it sees a book.xml file, it will
> try to build from that before it looks for a book.asciidoc.
> 
> Where did that book.xml come from?
> 
> No idea.  It was there when we got there.
> 
> It has <article> root tags instead of <book>, among other markup that
> will not work with the Atlas toolchain. If you can simply delete book.xml
> from the project, the book.asciidoc is all you need.
> 
> I think what we are asking is if someone would, please, import the book
> correctly.  We have worked on the previous 2 editions of this book, using
> DocBook.  The idea of spending a week or two or so figuring out all of this
> stuff, so that we can use Atlas, seems like time ill spent.
> 
> I would prefer to use DocBook.  If, however, we can get a working version
> of our book, in Atlas, without to much more trouble, we can all learn
> asciidoc.  For us to go through debugging the import, however, seems, as I
> said, misdirected energy.
> 
> Additionally, I noticed an issue in ch15 with this markup:
> 
> ++$$KEYCODE_+++<?lb?>+++CAMERA$$++
> 
> Our toolchain also doesn't support the <?lb?> processing instruction.
> 
> Interesting.  So why'd the import put them there?
> 
> If you're just trying to get those two parts of the term to break properly
> across a line, you might try this instead:
> 
> pass:[<literal role="keep-together">KEYCODE_</literal><literal role="keep-together">CAMERA</literal>]
> 
> If you fix the above and remove the book.xml, I believe your builds should
> start working, but please let me know if not and I'll take another look.
> 
> I'll give that a try.
> 
> -blake

## 

Amy Jollymore, Development Editor _|_ O'Reilly Media

Twitter https://twitter.com/amyjollymore _|_
Facebookhttps://www.facebook.com/JollymoreWordsmitheryCopyediting
 | LinkedIn http://www.linkedin.com/pub/amy-eden-jollymore/1/974/862

Desk 707.981.7153 | Cell 617.872.4508

_Do you read the O'Reilly Programming
*_blog*http://programming.oreilly.com/2013/10/ada-lovelace-an-indirect-and-reciprocal-influence.html
*? *

**Comment by zaremba** [comment]
Hi everyone,

Ally is going to pick up this discussion separately in an email thread.

Closing this ticket because this is no longer a support request.

Thanks,
Adam
