### ISSUE TITLE
Question: How do I add line breaks?

### ISSUE THREAD

**Issue by markgrover** [MakerPress/atlas-public-feedback#395]
Sorry for the noob question but this page (http://ano-chimera.herokuapp.com/books/1230000000065/ch04.html) says I can't and shouldn't use asciidoc method ("+" sign at the end of the line) and if I use a blank line myself in asciidoc, I get a line break and a blank line. I just want a line break, how do I go about doing that?

"+" sign at the end of line works locally but doesn't jive with Atlas. Thanks in advance!

**Comment by zaremba** [comment]
Hi @markgrover,

It's typically best to wait until a book is in production to deal with things like line breaks, because text flow can change considerably when the book is copyedited, etc.

I'd recommend just separating your content into paragraphs (with the blank line) or allowing it to break as it will while you are writing.

Thanks,
Adam
