### ISSUE TITLE
XInclude refuses to read chapter

### ISSUE THREAD

**Issue by andyoram** [MakerPress/atlas-public-feedback#403]
I'm working on a kind of transitional book that is in Atlas but uses DocBook:

http://atlas.labs.oreilly.com/books/1234000001776

A recent change produced some kind of odd internal error:

/usr/local/app/worker/tmp/pdf/1234000001776/book.xml
== Error 25

/usr/local/app/worker/tmp/pdf/1234000001776/book.xml:20: element include: XInclude error : could not load /usr/local/app/worker/tmp/pdf/1234000001776/ch08.xml, and no fallback was found

There is probably an XML error in Chapter 8, but this message is incorrect and provides no way to fix that error.

**Comment by christopappas** [comment]
Hello @andyoram 

In Chapter 8, there are 3 validity errors caused by `<emphasis>` tags being embedded in `<code>` tags. 2 on line 444 and 1 on line 448.  To fix this, you could use `<programlisting>` tags, which allow for inline markup, but be sure not to embed the `<programlisting>` inside a `<para>`. 

Also, while I was looking at your files, I noticed 3 more validity errors resulting from missing xref and indexterm references. I figured I should mention them while I'm here:

ch04.xml:758: element xref: validity error : IDREF attribute linkend references an unknown ID "fig_pgagent_step_dialog"
ch03.xml:15: element xref: validity error : IDREF attribute linkend references an unknown ID "sect_psql_helpa"
appb.xml:362: element indexterm: validity error : IDREF attribute startref references an unknown ID "idx_psql_helpa"

Let me know if there's anything else I can help with!

Thanks,
Chris
