### ISSUE TITLE
HTML builds on Atlas are failing

### ISSUE THREAD

**Issue by markgrover** [MakerPress/atlas-public-feedback#408]
The error looks like:
HTMLJob
Failed at 2014-06-30 08:43:06 UTC

Job failed
Full error:

Error 
  java.io.IOException: Server returned HTTP response code: 500 for URL:
  http://www.oasis-open.org/docbook/xml/4.5/docbookx.dtd
Transformation failed: Run-time errors were reported

**Comment by sandersk** [comment]
Hi @markgrover,

Thanks for the report, and apologies for the inconvenience. This error was caused by an outage on the OASIS site, which we use for DocBook validation in the HTML builds. The OASIS site is back up now, and HTML builds are now working as expected.

Moving forward, we'll update our build system to use local catalogs for validation, so it won't be susceptible to OASIS outages in the future.

Let us know if you encounter any further issues.

Sanders
