### ISSUE TITLE
Failed build

### ISSUE THREAD

**Issue by bandersonoreilly** [MakerPress/atlas-public-feedback#410]
Hello. Can't get this book to build:

http://ano-atlas2.herokuapp.com/books/1234000001863

Error message:

http://ano-atlas2.herokuapp.com/books/883/jobs/61937

Thanks!

**Comment by christopappas** [comment]
Hello @bandersonoreilly 

I had a look at the file throwing the error. A solution for this is to have a blank line before each opening passthrough delimiter (++++).

So instead of something like:

Networks
++++
&lt;screen&gt;

Try:

Networks

++++
&lt;screen&gt;

I made these modifications to the filename mentioned in the error message and the error is no longer thrown.

Let me know if you have any issues.

Thanks,
Chris

**Comment by bandersonoreilly** [comment]
Thank you Chris!
