### ISSUE TITLE
Need help with build errors

### ISSUE THREAD

**Issue by troymott** [MakerPress/atlas-public-feedback#416]
I have had no success sorting out the exact problem in these two files from this book:
http://ano-atlas2.herokuapp.com/books/1234000002119

Here are the errors:
asciidoc: ERROR: Section4.asciidoc: line 1022: section title not permitted in delimited block
asciidoc: ERROR: Section4.asciidoc: line 1075: section title not permitted in delimited block
asciidoc: ERROR: Section4.asciidoc: line 1083: section title not permitted in delimited block
asciidoc: ERROR: Section4.asciidoc: line 1163: section title not permitted in delimited block
asciidoc: ERROR: book.asciidoc: line 16: section title not permitted in delimited block
asciidoc: ERROR: Section5.appendix.asciidoc: line 10: section title not permitted in delimited block
asciidoc: ERROR: Section5.appendix.asciidoc: line 58: section title not permitted in delimited block
asciidoc: ERROR: Section5.appendix.asciidoc: line 113: section title not permitted in delimited block
asciidoc: ERROR: Section5.appendix.asciidoc: line 183: section title not permitted in delimited block
asciidoc: WARNING: Section5.appendix.asciidoc: line 200: missing section: [NOTE]
asciidoc: WARNING: Section5.appendix.asciidoc: line 252: section title out of sequence: expected level 1, got level 2

Any suggestions would be great. 

--Troy

**Comment by sandersk** [comment]
Hi @troymott,

This is fixed now. The issue was the markup used for two notes, this one in Section4.asciidoc:

```
 .Tip
 [NOTE]
=====================================================================
 Mark the board with a marker, to show where the tracks need to be cut.
=====================================================================
```

And this one in Section5.appendix.asciidoc:

```
 .Note
 [NOTE]
=====================================================================
 Pin number 6 (see Chapter 2) is a special pin: it's used as an output.
=====================================================================
```

When creating note delimiters in AsciiDoc for notes that are only one line, it's important to make sure the delimiters are not the same character length as the note text (give or take two characters). Otherwise, AsciiDoc misinterprets the note block as a two-line title (see documentation here: http://asciidoc.org/userguide.html#_two_line_titles), and this can cause cascading errors through the rest of the document.

I've gone ahead and fixed the delimiters in these two notes, and PDFs are now building successfully. Let us know if you encounter any further problems or have any questions.

Thanks,
Sanders

**Comment by troymott** [comment]
Thank you Sanders!!

--Troy
