### ISSUE TITLE
.mobi file generation failed

### ISSUE THREAD

**Issue by staffordvaughan** [MakerPress/atlas-public-feedback#44]
See details at http://ano-atlas2.herokuapp.com/books/146/jobs/7682.

**Comment by sandersk** [comment]
Hi Stafford,

The build failure was due to a tiny markup issue in Chapter 3, where there was a cross-reference marked up using id delimiters (square brackets instead of angle brackets). This resulted in a duplicate ID in the chapter, which caused errors in TOC generation in the Mobi.

Hope it's OK that I went ahead and made the following change in the source files in Chapter-3:-User-Management.asciidoc.

Changed:

If you're on the Enterprise plan the process will differ slightly, which is described in [[adding_agent_enterprise]].

To:

If you're on the Enterprise plan the process will differ slightly, which is described in <<adding_agent_enterprise>>.

I rebuilt the Mobi successfully, and you should be all set now.

Let me know if you have any questions or run into further problems.

Thanks,
Sanders

**Comment by staffordvaughan** [comment]
Nice one! Face palm for not thinking of that myself though :). Thanks for
fixing it.
