### ISSUE TITLE
Layout bug with images at the end of a chapter

### ISSUE THREAD

**Issue by staffordvaughan** [MakerPress/atlas-public-feedback#57]
If you take a look at the latest PDF export of http://ano-atlas2.herokuapp.com/books/1230000000581, the image at the end of chapter 6 is jumping into the chapter heading page of chapter 7.

**Comment by sandersk** [comment]
Hi Stafford,

Thanks for the report. This is another known bug with the PDF rendering software we use. There is currently no automated mechanism to prevent images floating from the end of one chapter to the beginning of the next, although we are in touch with the software vendor regarding this issue and are hoping we can have a fix in place soon.

In the meantime, when the book enters Production, we have manual fixes that we will implement to rectify these image placement problems. As part of the Production process, we review pagebreaks throughout the entire book and fix any layout issues before the book is released. You'll also have a chance to review the book during this QA period and provide feedback on layout.

Let us know if you have any questions or concerns about the above, and please keep the great feedback coming!

Thanks,
Sanders

**Comment by adamwitwer** [comment]
Hi Stafford,

As Sanders said, it is a bug with the PDF processor, particularly related to image floats. As a work around, you could deactivate the float on that image, like so:

```
[[fig-ticketfields-configured]]
.Configured set of ticket fields
[float="none"]
image::images/ticketfields-configured.png[Configured set of ticket fields]
```

Also, I noticed that you are including the figure title twice. The title is not needed in the brackets that follow the image path. However, our tools support alt text, so you could add alt text there, which will then flow throw to the various ebook formats and improve accessibility. For example:

```
[[fig-ticketfields-configured]]
.Configured set of ticket fields
[float="none"]
image::images/ticketfields-configured.png["Screen shot showing a list of active fields, some of which are editable"]
```

(Note that you should put quotes around the alt text.) If no alt text is included in the brackets, the build system automatically inserts the figure caption, which is why I said there is no need to include it twice.

I know that's more info than you asked for, but I just thought I'd mention it because I noticed it. Hope you find it helpful.

I'll go ahead and close this issue since it is a known bug that I'm tracking elsewhere and we have a work around for now. 

Thanks,
Adam

**Comment by staffordvaughan** [comment]
That's really useful Adam, I'll go back and remove the alt text. I realized it was alt text, but didn't realize that it would be automatically inserted from the figure if it wasn't included. Thanks for the tip!
