### ISSUE TITLE
Image not uploading

### ISSUE THREAD

**Issue by staffordvaughan** [MakerPress/atlas-public-feedback#58]
I'm trying to upload the image at https://www.dropbox.com/s/7p8ru23t04d3e9o/introduction-adminscreen.png (why can't we attach files onto GitHub, by the way?) while I have http://ano-atlas2.herokuapp.com/books/1230000000581/versions/master/editor/Chapter-1:-Introduction-to-Zendesk.asciidoc opened. Whenever I do it, the file does not stay on the server and the PDF comes out with a placeholder. What's the problem with this file?

**Comment by staffordvaughan** [comment]
Ok it's working now. Might have been a combination of the PDF being generated before the file was processed, and the fact that the HTML preview doesn't show files properly.

**Comment by sandersk** [comment]
Hi Stafford,

Great, glad you were able to get the upload working. Also, just wanted to clarify that you can indeed load images directly to the Git repo, instead of using the Image Manager. You can just add the image files in the images/ directory of a local checkout of the Atlas Git repo, and then use a "git push" to push them up to the server. Instructions for using a local Git checkout can be found in Chapter 6 of our Atlas docs, which are available here:

http://cdn.oreilly.com/atlas_docs.zip

Let us know if you have any further questions.

Thanks,
Sanders
