### ISSUE TITLE
"Builds" page should refresh to get updates for build status to change

### ISSUE THREAD

**Issue by adamwitwer** [MakerPress/atlas-public-feedback#59]
via @ALRubinger:

> 9) The "Builds" page needs to be refreshed to get updates for build
> status to change.  Push server event signaling when a build is done to
> the client (or poll).

I didn't see this request anywhere else, so I'm creating an issue for it.

**Comment by jhodgdon-drp** [comment]
I am seeing this problem too. As a bit of additional information, when I create a build, I get to the Builds page, and it shows a rotating in-progress icon indicating the build is in progress. But it never changes. I'm on Firefox 13.0 on Ubuntu if that makes a difference.

It seems like either there shouldn't be an in-progress icon (if I see one I expect it to change when the build is done), or the page should auto-refresh periodically so that it figures out the build is done.

**Comment by ehewitt** [comment]
+1 
My browser (Chrome 22.0.1229.79) never updates the build time. I have a book with a single short document that has been building for more than 30 minutes. The blue arrow keeps rotating, suggesting it's working, and the text says "less than a minute ago" forever. 

If I just risk it and navigate away to the Dashboard, then it shows Latest Builds as including the new build 34 minutes ago. But my build worked fine and the PDF looks great.

**Comment by AllenDowney** [comment]
+1
I get exactly the same behavior described by ehewitt
