### ISSUE TITLE
when I build my book I now get the title twice

### ISSUE THREAD

**Issue by JohnGarbutt** [MakerPress/atlas-public-feedback#66]
On the front page, I seem to get the title appearing twice. I don't think that used to happen.

This may be because I have broken something in my particular book, but not sure I changed anything that I would expect to make that happen. I did re-order a chapter.

**Comment by JohnGarbutt** [comment]
Awesome, you have fixed that for my book at least :-)

**Comment by sandersk** [comment]
Hi John,

Sorry about that. Earlier this week, we made some modifications to the code used to process title metadata. The title on the Metadata tab in the Atlas UI is now used to populate the title page in the ebook builds, and it is no longer necessary to include a book title in book-docinfo.xml or in the AsciiDoc files. I've removed the title from the book-docinfo.xml file, and rebuilt the PDF. If you look at the latest PDF build, the title is fixed now.

We did an audit earlier this week to try to catch all instances of now-redundant title markup, but must have missed Building an OpenStack Cloud. Apologies for the mistake.

Let us know if you encounter any further issues with the title page.

Best,
Sanders

**Comment by ehewitt** [comment]
I am seeing the same behavior, because I followed the sample in the atlas_docs_20120820 file on page 19, which includes a title element. 

So that should be removed from the documentation.

**Comment by jack-krupansky-BT** [comment]
This problem is happening to be right now. This is the second time. in the past month.
In my case, I see:

"
Solr 4.x Deep Dive
Solr 4.x Deep Dive - Early Access Release #5 
"

The title is correct in both cases, and the subtitle shows up only on the second line. This happens on both the title page and at the top of the copyright page.

I don't recall exactly how I made it go away the previous time, a couple of weeks ago, but I think I created a dummy book.xml in the GUI editor and then build worked... sort of - I had to completely re-do my file ordering, which is a pain since I have 50 or so files.

I don't have a title in book-info.xml.

**Comment by adamwitwer** [comment]
Hi @jack-krupansky-BT. There was a `<title>` in the `book-docinfo.xml` file, which I just removed. The file-naming convention for the metadata file is a little bit different in AsciiDoc (book-docinfo.xml instead of bookinfo.xml). The next PDF build should not have two titles. It's building now.

**Comment by jack-krupansky-BT** [comment]
Thanks... the second title did go away, but... my subtitle went away as well. I've been changing field values in the metadata just to see if changes might trigger a reload/regen from the metadata. Sigh.

Not sure why a title would magically appear in book-docinfo.xml. I certainly didn't put it there.

**Comment by jack-krupansky-BT** [comment]
I tried a few things and a couple of builds, but I am stuck with the problem I last mentioned - the subtitle is not appearing. And I checked book-info.xml to make sure it had no title.

I'm at a loss for what to try next.

**Comment by sandersk** [comment]
Hi @jack-krupansky-BT,

Actually, while there should not be a <title> in book-docinfo.xml, you do need to include the <subtitle> there, so I added it in. If you check the latest PDF build I just did, I believe the title page should now be rendering as you expect.

Let us know if you encounter any further issues.

Thanks,
Sanders

**Comment by jack-krupansky-BT** [comment]
Thanks, I see the sub-title on the title page. But... it doesn't show up on the copyright page like it used to.

For the moment, this is fine, although I'd like to understand why it was working.

BTW, I tried to review all my changes since I published a PDF on Friday and I could only go back 3 pages before I got a 500 server error. I retried and hit the same 500.

But, I'm pretty sure that I had built a PDF on Saturday that had the expected title and subtitle, without either a title or subtitle in book-info.xml. And there were no edits to book-info.xml back as far as I could go on Saturday.

**Comment by sandersk** [comment]
Hi @jack-krupansky-BT,

I added handling to the template to your book to display the subtitle on the copyright page; previously, there was no handling so I'm fairly sure you did not see a subtitle on the copyright page in the past.

A 500 on the changes tab usually indicates a functionality bug due to a character-encoding issue. We're currently working on improving the editor and will be revisiting the Changes tab functionality, so stay tuned.

Sanders
