### ISSUE TITLE
Build Gets Stuck After Forced Push

### ISSUE THREAD

**Issue by ALRubinger** [MakerPress/atlas-public-feedback#74]
When committing changes that rewrite the index history using forced push:

  "git push atlas master -f" 

...subsequent build requests will get "stuck", spinning forever in "pending".

**Comment by runemadsen** [comment]
Hey Andrew

What book are we talking about here?

**Comment by adamwitwer** [comment]
Hi Rune,

It's this book:

http://atlas.labs.oreilly.com/books/1230000000485

Also, please note that this is the same project that we had problems with before, as described here:

https://github.com/MakerPress/atlas-public-feedback/issues/42

Adam

**Comment by runemadsen** [comment]
Thanks, I'll take a look right now.

Quick question: Why are you using -f?
- Rune

**Comment by ALRubinger** [comment]
The force flag is needed to push changes after performing an interactive
rebase which rewrites history (reordering, squashing commits, etc).

**Comment by odewahn** [comment]
Hey, Rune.  We need to flush the caches for this off the workers machines to clear this up.  It's a frequent enough thing that we should probably either have a worker to do or some sort of rake task.  

And, yes, "-f" is evil in Atlas world... It's a shame that git actually suggests using it.  I'd like to understand, as well, how you're using it.

Andrew

----- Original Message -----

**Comment by runemadsen** [comment]
The problem we're seeing has actually been solved in the current HEAD of atlas-workers, however we're pending a server migration this week to update the new code. When the new changes have been deployed, I don't think you'll see this error anymore.

There was one tiny error in the HTML worker that has been fixed now and will be updated soon.

**Comment by runemadsen** [comment]
Okay, I just built your book, and it's working now. Until we've migrated the server, you'll see errors in the PDF worker every time you -f. Hopefully it's only a matter of a few days, and let me know if you want me to reset the repo.

**Comment by ALRubinger** [comment]
I'd like to address Andrew's questions about the usage of forced pushes.

The feature is not, in and of itself, evil.  Git allows us to rewrite
commit messages, reorder commits, or squash N commits together into one;
these are all very helpful tools in keeping a sane version history.
 Consider that every save in Atlas triggers a commit...we don't necessarily
want to keep a commit for every time we hit "save".  Also, adding images is
something we do via the Git command-line, and that'd be a separate commit.
 Ideally, every commit should be able to stand on its own as an atomic
unit, so it's frequent that we squash commits together such that a section
or chapter all goes in together.

In this sense, it's natural that we'd need to push these changes to the
Atlas repository.

The time that rewriting history becomes "evil" is when folks upstream are
working off a fork, only to find that the past of the upstream has been
rewritten.  For this reason, it's advised that we don't ever force push
commits to the upstream.  In our case, the upstream repo is on GitHub, and
Atlas is merely another remote which we use as our build server and one of
the authoring servers.

**Comment by runemadsen** [comment]
That all makes a lot of sense, thanks for that. Atlas will work perfectly with a forced push as soon as we migrate to the new server setup.

The reason why your builds keeps failing is that Atlas isn't just a build server. It's a distribution system that relies on the git history. For example, as we integrate the ability to export your book as a website, we need the ability to publish your book files to S3 / Cloudfront. We don't want to upload entire gigabytes of files every time you update your book, so instead we use the git commit history to search for changed files and only upload those assets. 

Your build kept crashing because the "Last Build Commit SHA" was not present in the repo anymore. You probably squashed it into another commit. This was easy to circumvent, as we just upload all files if this problem arises, but there are some effects to not treating Atlas like upstream right now.

It's great to come across these things though, as it helps us build a more robust system.

**Comment by odewahn** [comment]
Hey, Andrew.  Thanks for this clarifications -- it's great to understand how you're using git.  It's super helpful.  Also, your distinction between "commit" and "save" is well-taken and something we've discussed a lot among ourselves, so it's great to see that it's not been totally academic.  We're trying to thread a needle of supporting all features of git for advanced users, but hiding git from people who don't want to bother with it. You're clearly in the former category!  

When I said "evil," I was being facetious.  The only way it's evil to us is that if you force push to the Atlas repo (which is fine), it causes our build process to hang because the first thing "build" does is pull the changes to a local copy on the build server on another machines. The force push usually winds up in a conflict that forces us to clear the caches manually.  (We haven't automated that part yet.)  

So, that's the context of "evil" -- not that it's an evil feature of git, but that it's use results in manual work for us...  

Sorry for the confusion, and thanks for the really great explanation.

Andrew

----- Original Message -----

**Comment by ALRubinger** [comment]
By the way you guys have been awesome.  We opted into this process 
hoping for exactly what we're getting - a chance to improve a system as 
its being built.  We're used to hacking software to fit our needs, and 
we rely on the same kind of input from our users.  Thanks for running a 
great project and being so responsive.

And I understood what you meant by "evil", a lot of folks will actually 
say "never force push", but I think the distinction about when it's 
appropriate is worth making just in case. :)

**Comment by odewahn** [comment]
Thanks, Andrew.  That means a lot -- we've been working hard to make a tool that we'd want to use ourselves, so it's great to hear that you're enjoying the process.  Thanks for sticking through the warts as we get it going.

Andrew

----- Original Message -----

**Comment by ALRubinger** [comment]
Hmm...I'd thought this was fixed, but have a few hanging builds now after a forced push.  Thoughts?

**Comment by runemadsen** [comment]
Thanks, I'll take a look at what's going on.

**Comment by runemadsen** [comment]
It seems like the system still has some problems when it comes to forced pushes. I've fixed it for now by resetting the repos on our build server. I'll look at Monday and make sure that we won't run into this problem again.

**Comment by ALRubinger** [comment]
As always, appreciated.
