### ISSUE TITLE
Not sure what's causing this dash issue

### ISSUE THREAD

**Issue by staffordvaughan** [MakerPress/atlas-public-feedback#79]
If you open http://ano-atlas2.herokuapp.com/books/1230000000581/versions/master/editor/Chapter-6:-Fields-and-Data-Capture.asciidoc/preview and check the first sentence of "Reading the List of Ticket Fields", you'll notice that the second double-dash, which is connected to a cross-reference, isn't rendering problem. Is that something wrong with my syntax?

**Comment by adamwitwer** [comment]
Hi Stafford. There's nothing wrong with your syntax. I've noticed that AsciiDoc sometimes doesn't convert the -- to a real em dash if it occurs next to an xref or some other punctuation, such as closing quotes. In these cases, we've been using a workaround of inserting a true em dash instead of the double dash. Are you on a Mac? If so, the keyboard shortcut for an em dash is alt+shift+dash.

**Comment by staffordvaughan** [comment]
Thanks Adam.
