### ISSUE TITLE
Altas doesn't format double quotes properly

### ISSUE THREAD

**Issue by jimwebber** [MakerPress/atlas-public-feedback#81]
When using the asciidoc quoting mechanism:

```
``I like burritos''
```

It's rendered in the PDF literally as:

```
`I like burritos'
```

Rather than being:

"I like burritos"

**Comment by sandersk** [comment]
Hi Jim,

I took a look at the AsciiDoc files for your book, and found a couple instances where the AsciiDoc quote markers were reversed--e.g.:

```
''links``
```

instead of:

```
``links''
```

See the Changes tab in Atlas for a couple corresponding fixes I made. I'm assuming these are the instances you're referring to where the markers are being rendered literally in the PDF? If not, could you point me to another instance where you're seeing the problem.

Assuming that solves the issue with the ticks being rendering literally, in troubleshooting your issue, I actually discovered a related bug in our AsciiDoc conversion where the correct quotation markup:

   ``links''

Results in quotes being dropped from the PDF output. We're actively working on a fix for that right now, and hope to have that in place early next week in conjunction with a major update we have scheduled for our build infrastructure.

Apologies for any short-term inconvenience. If you need to have the quote marks displayed in the meantime, you can enter the actual characters literally in the document (on the Mac, the keyboard shortcut for a left double quote is Option-[ and the keyboard shortcut for a right double quote is Option-Shift-[), or you can use Unicode codepoints (&#8220; for left double quote, and &#8221; for right double quote)

Again, very sorry for any inconvenience here. Please let me know if you have any further questions, or encounter any other issues.

Best,
Sanders

**Comment by sandersk** [comment]
Hi Jim,

Just wanted to follow up quickly and let you know that we've now got the fix in place for the AsciiDoc ``quote'' markup, and the resulting double quotes are now rendering properly in the ebook output. But if you encounter any further issues or have any questions, please let us know.

Best,
Sanders
