### ISSUE TITLE
New Chapters Require Double Newline at EOF

### ISSUE THREAD

**Issue by ALRubinger** [MakerPress/atlas-public-feedback#86]
For new Chapters to be registered by Atlas, there must be at least a double newline character between the end of the previous chapter file and the beginning of the new chapter file.  Else the following:

  "== ChapterName"

...appears in plaintext in the output, with no proper Chapter formatting or Table of Contents reflected.

**Comment by sandersk** [comment]
Hi Andrew,

Yes, that's correct. When you're building a book.asciidoc file manually with include:: statements, they need to be separated by at least 2 newline characters, e.g.

```
include::Chapter00-Prelude.asciidoc[]

include::Chapter01-Continuity.asciidoc[]
```

When you do your builds via the Build tab in Atlas, it automatically generates the book.asciidoc file, and should do so with double-newlines between include:: statements. Did this not happen correctly for your book? If so, we may have a bug somewhere and will look into it.

Best,
Sanders

**Comment by ALRubinger** [comment]
Ah, thank you.

I hadn't realized I could place the newlines in "book.asciidoc", so I 
had to place them in the chapter files themselves.  This makes sense (I 
had not used the Atlas editor to generate "book.asciidoc", did that 
manually).

Is this the desired functionality?  Would it make sense to have Atlas 
automatically insert the necessary whitespace between includes?  ie. 
What's the use case where the white space _would not_ be desired?  If 
you wanted to maintain continuity in the generated text but split the 
source files?

**Comment by sandersk** [comment]
Hi Andrew,

We're already inserting the necessary whitespace between includes as part of the Atlas build process. When you go to the Build tab in Atlas and select your chapters there, a book.asciidoc file is generated on the fly, which  automatically inserts the necessary whitespace between includes. I tested this on your book just now, and confirmed this was working. 

Were you getting different results earlier? If so, I suspect the issue was simply one of caching. In order to have Atlas regenerate a fresh book.asciidoc, you just need to move a chapter or two off the "Files to Build" pane and then back onto the "Files to Build" pane.

Let me know if you still encounter problems here.

Thanks,
Sanders

**Comment by ALRubinger** [comment]
Yes, caching was the issue.  Using the automated builder in Atlas works
just fine.

Thanks!
